import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { shouldRefreshAccess } from '../src/shared/authSession.js'

function source(path) {
  return readFileSync(new URL(path, import.meta.url), 'utf8')
}

test('access token refreshes before expiry and when missing', () => {
  const now = Date.parse('2026-06-19T12:00:00Z')
  assert.equal(shouldRefreshAccess('2026-06-19T12:10:00Z', true, now), false)
  assert.equal(shouldRefreshAccess('2026-06-19T12:00:30Z', true, now), true)
  assert.equal(shouldRefreshAccess('', false, now), true)
})

test('account login uses backend security proxy and inactivity timeout', () => {
  const sessionApi = source('../src/api/authSessionApi.js')
  const clientApi = source('../src/api/client.js')
  const personal = source('../src/personal/App.vue')
  const personalRouter = source('../src/personal/router.js')
  const team = source('../src/team/App.vue')
  const teamRouter = source('../src/team/router.js')
  const authPanel = source('../src/components/AuthPanel.vue')
  const authCallback = source('../src/shared/views/AuthCallback.vue')
  const backendMain = source('../../backend/app/main.py')
  const backendAuth = source('../../backend/app/auth.py')
  const dockerfile = source('../Dockerfile')
  const compose = source('../../docker-compose.yml')
  const envExample = source('../../.env.example')
  assert.match(sessionApi, /VITE_AUTH_IDLE_TIMEOUT_MINUTES/)
  assert.match(sessionApi, /VITE_AUTH_MAX_SESSION_HOURS/)
  assert.match(sessionApi, /setupAuthActivityTracking/)
  assert.match(sessionApi, /sessionTimedOut/)
  assert.match(sessionApi, /\/auth\/account\/captcha/)
  assert.match(sessionApi, /\/auth\/account\/sms\/send/)
  assert.doesNotMatch(sessionApi, /\/auth\/account\/login\/sms/)
  assert.doesNotMatch(sessionApi, /\/auth\/account\/login\/password/)
  assert.doesNotMatch(sessionApi, /\/auth\/account\/register/)
  assert.doesNotMatch(sessionApi, /\/auth\/account\/password\/reset/)
  assert.doesNotMatch(sessionApi, /\/auth\/local\//)
  assert.doesNotMatch(sessionApi, /loginWithPassword/)
  assert.doesNotMatch(sessionApi, /loginWithSms/)
  assert.doesNotMatch(sessionApi, /registerWithPassword/)
  assert.doesNotMatch(sessionApi, /resetAuthPassword/)
  assert.match(sessionApi, /startSsoLogin/)
  assert.match(sessionApi, /finishSsoLogin/)
  assert.match(sessionApi, /code_challenge_method', 'S256'/)
  assert.match(sessionApi, /\/auth\/account\/sso\/start/)
  assert.match(sessionApi, /\/auth\/account\/sso\/token/)
  assert.match(sessionApi, /data\.returnTo \|\| returnTo/)
  assert.match(sessionApi, /\/auth\/account\/token\/refresh/)
  assert.doesNotMatch(sessionApi, /authApi\.post\('\/login\/sms'/)
  assert.doesNotMatch(sessionApi, /authApi\.post\('\/sms\/send'/)
  assert.match(clientApi, /endsWith\('\/auth\/config'\)/)
  assert.match(personal, /setupAuthActivityTracking/)
  assert.match(personal, /router\.replace\('\/'\)/)
  assert.match(personal, /auth-callback/)
  assert.match(personalRouter, /\/auth\/callback/)
  assert.match(team, /setupAuthActivityTracking/)
  assert.match(team, /authCallback/)
  assert.match(teamRouter, /team-auth-callback/)
  assert.match(authPanel, /使用 WXY LAB 统一登录/)
  assert.match(authPanel, /auth-ambient/)
  assert.match(authPanel, /auth-workbench/)
  assert.match(authPanel, /RES-00000024/)
  assert.match(authPanel, /qr-mark/)
  assert.doesNotMatch(authPanel, /class="sso-button"[\s\S]*?<img :src="logo" alt="" \/>/)
  assert.match(authPanel, /startSsoLogin/)
  assert.doesNotMatch(authPanel, /密码登录/)
  assert.doesNotMatch(authPanel, /短信登录/)
  assert.doesNotMatch(authPanel, /name="register"/)
  assert.doesNotMatch(authPanel, /重置密码/)
  assert.match(authCallback, /finishSsoLogin/)
  assert.match(backendMain, /AUTH_PROXY_LIMITS/)
  assert.match(backendMain, /enforce_auth_proxy_limit/)
  assert.match(backendMain, /client_ip\(request\)/)
  assert.match(backendMain, /account_sso_token_request/)
  assert.match(backendMain, /SSO_STATE_COOKIE/)
  assert.match(backendMain, /\/api\/auth\/account\/sso\/start/)
  assert.match(backendMain, /\/api\/auth\/account\/sso\/token/)
  assert.match(backendMain, /camera=\(self\), microphone=\(\), geolocation=\(\)/)
  assert.match(backendMain, /\/api\/auth\/account\/sms\/send/)
  assert.match(backendMain, /\/api\/auth\/account\/login\/sms/)
  assert.match(backendMain, /legacy_login_retired/)
  assert.match(backendMain, /\/api\/auth\/account\/token\/refresh/)
  assert.match(backendMain, /status_code=429/)
  assert.match(backendAuth, /ACCOUNT_SSO_AUTHORIZE_URL/)
  assert.match(backendAuth, /\/sso\/authorize/)
  assert.match(backendAuth, /sso_redirect_uri/)
  assert.match(dockerfile, /ARG VITE_AUTH_IDLE_TIMEOUT_MINUTES/)
  assert.match(compose, /VITE_AUTH_MAX_SESSION_HOURS/)
  assert.match(envExample, /ACCOUNT_SSO_REDIRECT_URI/)
  assert.match(envExample, /VITE_AUTH_IDLE_TIMEOUT_MINUTES=720/)
  assert.match(envExample, /VITE_AUTH_MAX_SESSION_HOURS=168/)
})
