import test from 'node:test'
import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'

function source(path) {
  return readFileSync(new URL(path, import.meta.url), 'utf8')
}

function contrastRatio(foreground, background) {
  const luminance = (hex) => {
    const channels = [1, 3, 5].map((offset) => Number.parseInt(hex.slice(offset, offset + 2), 16) / 255)
      .map((value) => value <= 0.04045 ? value / 12.92 : ((value + 0.055) / 1.055) ** 2.4)
    return channels[0] * 0.2126 + channels[1] * 0.7152 + channels[2] * 0.0722
  }
  const values = [luminance(foreground), luminance(background)].sort((left, right) => right - left)
  return (values[0] + 0.05) / (values[1] + 0.05)
}

test('personal web routes share the hardware root while legacy pages only redirect', () => {
  const paths = source('../src/shared/appPaths.js')
  const directNginx = source('../../deploy/nginx-component-warehouse-8080.conf')
  const personalManifest = source('../public/manifest.webmanifest')
  const teamManifest = source('../public/team-manifest.webmanifest')
  const edaLibrary = source('../src/shared/views/EdaLibrary.vue')
  const edaGuide = source('../src/shared/views/EdaGuide.vue')
  assert.match(paths, /APP_ROOT = '\/hardware'/)
  assert.match(paths, /SERVICE_ROOT = APP_ROOT/)
  assert.match(paths, /PERSONAL_BASE = `\$\{APP_ROOT\}\//)
  assert.match(paths, /TEAM_BASE = '\/component-warehouse\/team\/'/)
  assert.match(directNginx, /location \/hardware\/api\//)
  assert.match(directNginx, /location \/hardware\/ \{[\s\S]*?\/hardware\/index\.html/)
  assert.match(directNginx, /location ~ \^\/component-warehouse\/personal\/\(\.\*\)\$ \{[\s\S]*?return 301 \/hardware\/\$1\$is_args\$args/)
  assert.match(directNginx, /location \/component-warehouse\/team\/ \{[\s\S]*?\/component-warehouse\/team\/index\.html/)
  assert.match(directNginx, /location ~ \^\/hardware\/team\/\(\.\*\)\$ \{[\s\S]*?return 301 \/component-warehouse\/team\/\$1\$is_args\$args/)
  assert.match(personalManifest, /"start_url": "\/hardware\/"/)
  assert.match(teamManifest, /"start_url": "\/component-warehouse\/team\/"/)
  assert.match(edaLibrary, /\/hardware\/downloads\/WXYLAB-AD-Sync-latest-win-x64\.zip/)
  assert.match(edaGuide, /\/hardware\/downloads\/WXYLAB-AD-Sync-latest-win-x64\.zip\.sha256/)
  assert.doesNotMatch(`${edaLibrary}\n${edaGuide}`, /ComponentWarehouse-AD-Sync-latest/)
})

test('team detail keeps privileged actions in the three-dot menu', () => {
  const text = source('../src/team/views/Components.vue')
  assert.match(text, /<el-dropdown/)
  assert.match(text, /selected\.can_edit_quantity/)
  assert.match(text, /command="remove"/)
  assert.doesNotMatch(text, /<template #actions>[\s\S]{0,300}移出团队器件库/)
})

test('personal inventory price import and valuation remain optional and private-facing', () => {
  const page = source('../src/views/Components.vue')
  const dashboard = source('../src/views/Dashboard.vue')
  const card = source('../src/components/inventory/InventoryComponentCard.vue')
  const workspace = source('../src/components/inventory/ComponentCreateWorkspace.vue')
  const client = source('../src/api/client.js')
  const teamPage = source('../src/team/views/Components.vue')
  assert.match(page, /导入价格对账单/)
  assert.match(page, /confirmPriceStatementImport/)
  assert.match(page, /priceStatementFile/)
  assert.match(page, /库存数量不会变化/)
  assert.match(page, /v-model="form\.average_unit_price"/)
  assert.match(workspace, /均价（元\/件，可空）/)
  assert.match(card, /均价 \{\{ averagePriceLabel \}\}\/件/)
  assert.match(card, /maximumFractionDigits: 4/)
  assert.match(dashboard, /全部库存总值/)
  assert.match(dashboard, /可用库存总值/)
  assert.match(dashboard, /cw\.dashboard\.inventory-values-visible/)
  assert.match(dashboard, /showInventoryValues \? View : Hide/)
  assert.match(dashboard, /localStorage\.setItem/)
  assert.match(client, /\/import\/price-statement\/preview/)
  assert.match(client, /\/import\/price-statement\/commit/)
  assert.doesNotMatch(teamPage, /average_unit_price|价格对账单|库存总值/)
})

test('usage records are collapsed and lazy loaded', () => {
  const text = source('../src/components/inventory/InventoryComponentDetail.vue')
  assert.match(text, /usageExpanded/)
  assert.match(text, /emit\('load-usage', 20\)/)
  assert.match(text, /max-height: 360px/)
})

test('personal component stream uses a compact cancellable response and smooth floating search', () => {
  const page = source('../src/views/Components.vue')
  const client = source('../src/api/client.js')
  assert.match(client, /\/components\/card-page/)
  assert.match(client, /\{ \.\.\.config, params \}/)
  assert.match(page, /new AbortController\(\)/)
  assert.match(page, /Promise\.allSettled\(\[loadCategories\(\), loadImportBatches\(\), loadCustomLabels\(\)\]\)/)
  assert.match(page, /v-loading="loading && !groups\.length"/)
  assert.match(page, /class="floating-search"/)
  assert.match(page, /backdrop-filter: blur\(20px\) saturate\(145%\)/)
  assert.match(page, /new IntersectionObserver/)
  assert.match(page, /prefers-reduced-motion: reduce/)
  assert.doesNotMatch(page, /_display:/)
  const card = source('../src/components/inventory/InventoryComponentCard.vue')
  assert.match(card, /Array\.isArray\(props\.item\.card_chips\)/)
  assert.match(card, /props\.item\.card_usage \|\| componentOneLineUsage/)
})

test('component detail exposes inventory lots and component-scoped AI question UI', () => {
  const text = source('../src/components/inventory/InventoryComponentDetail.vue')
  const page = source('../src/views/Components.vue')
  const teamPage = source('../src/team/views/Components.vue')
  const client = source('../src/api/client.js')
  const teamClient = source('../src/team/api.js')
  const removalConfirmation = source('../src/shared/confirmInventoryLotRemoval.js')
  assert.match(text, /库存批次 \/ 采购渠道/)
  assert.match(text, /新增批次/)
  assert.match(text, /@click="\$emit\('consume-lot', lot\)"/)
  assert.match(text, /lotConsumeIds\.has\(lot\.id\)/)
  assert.match(page, /:lot-consume-ids="lotConsumeIds"/)
  assert.match(teamPage, /:lot-consume-ids="lotConsumeIds"/)
  assert.match(text, /lot\.can_delete/)
  assert.match(text, /@click="\$emit\('delete-lot', lot\)"/)
  assert.match(page, /@delete-lot="deleteInventoryLot"/)
  assert.match(teamPage, /@delete-lot="deleteInventoryLot"/)
  assert.match(client, /api\.delete\(`\/components\/\$\{id\}\/lots\/\$\{lotId\}`\)/)
  assert.match(teamClient, /teamApi\.delete\(`\$\{base\}\/libraries\/\$\{id\}\/components\/\$\{itemId\}\/lots\/\$\{lotId\}`\)/)
  assert.match(page, /confirmInventoryLotRemoval/)
  assert.match(teamPage, /confirmInventoryLotRemoval/)
  assert.match(removalConfirmation, /ElMessageBox\.confirm/)
  assert.match(removalConfirmation, /ElMessageBox\.prompt/)
  assert.match(removalConfirmation, /二次确认去除库存/)
  assert.match(removalConfirmation, /inputValidator/)
  assert.match(page, /Promise\.allSettled/)
  assert.match(teamPage, /Promise\.allSettled/)
  const personalConsume = page.slice(page.indexOf('async function consumeInventoryLot'), page.indexOf('async function deleteInventoryLot'))
  const teamConsume = teamPage.slice(teamPage.indexOf('async function consumeInventoryLot'), teamPage.indexOf('async function quickConsume'))
  assert.match(personalConsume, /applyInventoryLotConsumption/)
  assert.match(teamConsume, /applyInventoryLotConsumption/)
  assert.doesNotMatch(personalConsume, /await loadLots\(\)|await load\(\)/)
  assert.doesNotMatch(teamConsume, /await loadLots\(\)|await load\(\)/)
  const inventorySync = page.slice(page.indexOf('inventoryChannel.onmessage'), page.indexOf('onBeforeUnmount', page.indexOf('inventoryChannel.onmessage')))
  assert.match(inventorySync, /quantityPatch/)
  assert.doesNotMatch(inventorySync, /\bload\(\)/)
  assert.match(text, /问这个元器件/)
  assert.match(text, /emit\('ask-ai', question\)/)
  assert.match(text, /packageTagStyle/)
  assert.match(page, /移除记录/)
  assert.match(page, /removeSelectedComponent/)
  assert.match(page, /不会释放或复用/)
  assert.match(page, /deleteComponent/)
})

test('PCB empty state is separate from request failure handling', () => {
  const text = source('../src/team/views/Pcbs.vue')
  assert.match(text, /暂无 PCB/)
  assert.match(text, /const libraryData = await getLibrary/)
  assert.match(text, /const pcbData = await listPcbs/)
})

test('login panel and account menu route account management to unified SSO center', () => {
  const auth = source('../src/components/AuthPanel.vue')
  assert.match(auth, /使用 WXY LAB 统一登录/)
  assert.match(auth, /sso-button/)
  assert.match(auth, /auth-ambient/)
  assert.match(auth, /auth-workbench/)
  assert.match(auth, /workbench-grid/)
  assert.match(auth, /width: 100%/)
  assert.match(auth, /grid-template-columns: minmax\(0, 560px\) minmax\(0, 510px\)/)
  assert.match(auth, /max\(24px, calc\(\(100vw - 1180px\) \/ 2\)\)/)
  assert.match(auth, /background-size: 64px 64px, 64px 64px, 420px 420px, 520px 520px/)
  assert.doesNotMatch(auth, /filter: blur/)
  assert.doesNotMatch(auth, /auth-grid-drift/)
  assert.doesNotMatch(auth, /auth-band-slide/)
  assert.doesNotMatch(auth, /will-change/)
  assert.match(auth, /auth-card-enter/)
  assert.match(auth, /animation-iteration-count: 1/)
  assert.match(auth, /qr-scan-blip/)
  assert.match(auth, /prefers-reduced-motion: reduce/)
  assert.match(auth, /grid-template-columns: minmax\(0, 1fr\)/)
  assert.match(auth, /place-content: start stretch/)
  assert.match(auth, /RES-00000024/)
  assert.match(auth, /qr-mark/)
  assert.doesNotMatch(auth, /class="sso-button"[\s\S]*?<img :src="logo" alt="" \/>/)
  assert.match(auth, /startSsoLogin/)
  assert.match(auth, /serviceError/)
  assert.match(auth, /auth-card-head/)
  assert.doesNotMatch(auth, /auth-capabilities/)
  assert.doesNotMatch(auth, /auth-status-strip/)
  assert.match(auth, /lang="zh-CN" translate="no"/)
  assert.doesNotMatch(auth, /密码登录/)
  assert.doesNotMatch(auth, /短信登录/)
  assert.doesNotMatch(auth, /name="register"/)
  assert.doesNotMatch(auth, /重置密码/)
  assert.doesNotMatch(auth, /errorMessage\(error, '操作失败'\)/)

  const account = source('../src/shared/components/AccountPopover.vue')
  const sessionApi = source('../src/api/authSessionApi.js')
  assert.match(account, /统一账号中心/)
  assert.match(account, /账号管理/)
  assert.match(account, /v-model:visible="popoverVisible"/)
  assert.match(account, /cw-open-account-settings/)
  assert.match(account, /openAccountProfile/)
  assert.match(account, /fetchAccountProfile/)
  assert.match(account, /resolveAccountAvatarUrl/)
  assert.match(account, /showAvatarImage/)
  assert.match(account, /@error="markAvatarFailed"/)
  assert.match(account, /class="account-avatar account-avatar-sm"/)
  assert.match(account, /class="account-avatar profile-avatar"/)
  assert.match(account, /accountUser/)
  assert.match(account, /displayUser/)
  assert.match(account, /accountUser\.value = user/)
  assert.match(account, /refreshProfile\(\)/)
  assert.match(account, /border-radius: 8px/)
  assert.match(account, /cw-account-popover/)
  assert.match(sessionApi, /ACCOUNT_PROFILE_PATH = '\/account\/profile'/)
  assert.match(sessionApi, /accountProfileUrl/)
  assert.match(sessionApi, /resolveAccountAvatarUrl/)
  assert.match(sessionApi, /localAuthApi\.get\('\/auth\/account\/me'/)
  assert.match(sessionApi, /data\.user \|\| data\.account \|\| data/)
  assert.match(sessionApi, /user\?\.avatarUrl \|\| data\.avatarUrl/)
  assert.doesNotMatch(account, /security-code/)
  assert.doesNotMatch(account, /更换手机号/)
  assert.doesNotMatch(account, /修改密码/)
  assert.doesNotMatch(account, /刷新会话/)
  assert.doesNotMatch(account, /captchaError/)
})

test('app shell is marked as Chinese and opts out of browser translation', () => {
  const html = source('../index.html')
  const personal = source('../src/personal/App.vue')
  const team = source('../src/team/App.vue')
  const about = source('../src/views/About.vue')
  const personalMain = source('../src/personal/main.js')
  const personalSw = source('../public/sw.js')
  const teamMain = source('../src/team/main.js')
  const teamSw = source('../public/team-sw.js')
  const manifest = source('../public/manifest.webmanifest')
  const teamManifest = source('../public/team-manifest.webmanifest')
  const vite = source('../vite.config.js')
  const dockerfile = source('../Dockerfile')
  const compose = source('../../docker-compose.yml')
  const installButton = source('../src/shared/components/InstallAppButton.vue')
  const pwaInstall = source('../src/shared/pwaInstall.js')
  assert.match(html, /<html lang="zh-CN" translate="no" class="notranslate">/)
  assert.match(html, /<meta name="google" content="notranslate" \/>/)
  assert.match(html, /name="application-name"/)
  assert.match(html, /name="apple-mobile-web-app-title"/)
  assert.match(html, /name="mobile-web-app-capable" content="yes"/)
  assert.match(html, /<body class="notranslate" translate="no">/)
  assert.match(manifest, /"name": "WXY LAB Hardware"/)
  assert.match(manifest, /"short_name": "WXY Hardware"/)
  assert.match(manifest, /"scope": "\/hardware\/"/)
  assert.doesNotMatch(manifest, /"short_name": "CW"/)
  assert.match(teamManifest, /"name": "WXY LAB Hardware Workspace 团队版"/)
  assert.match(teamManifest, /"short_name": "团队版维护中"/)
  assert.match(teamManifest, /"scope": "\/"/)
  assert.doesNotMatch(teamManifest, /CW Team/)
  assert.match(vite, /VITE_PWA_PERSONAL_NAME/)
  assert.match(vite, /apple-mobile-web-app-title/)
  assert.match(dockerfile, /ARG VITE_PWA_PERSONAL_NAME/)
  assert.match(compose, /VITE_PWA_TEAM_NAME/)
  assert.match(pwaInstall, /beforeinstallprompt/)
  assert.match(pwaInstall, /event\.preventDefault\(\)/)
  assert.match(pwaInstall, /prompt\.prompt\(\)/)
  assert.match(pwaInstall, /appinstalled/)
  assert.match(pwaInstall, /canInstallPwa/)
  assert.match(pwaInstall, /canShowPwaInstall/)
  assert.match(pwaInstall, /hasNativeInstallPrompt/)
  assert.match(pwaInstall, /outcome: 'manual'/)
  assert.match(installButton, /安装应用/)
  assert.match(installButton, /canShowPwaInstall/)
  assert.match(installButton, /ElMessageBox\.alert/)
  assert.match(installButton, /添加到主屏幕/)
  assert.match(personalMain, /navigator\.serviceWorker\.register\(`\$\{PERSONAL_BASE\}sw\.js`, \{ scope: PERSONAL_BASE \}\)/)
  assert.match(teamMain, /navigator\.serviceWorker\.register\(`\$\{TEAM_BASE\}team-sw\.js`, \{ scope: TEAM_BASE \}\)/)
  assert.match(personalSw, /PERSONAL_ROOT/)
  assert.match(personalSw, /manifest\.webmanifest/)
  assert.match(teamSw, /TEAM_ROOT/)
  assert.match(about, /<install-app-button \/>/)
  assert.match(about, /management-actions/)
  assert.doesNotMatch(personal, /<install-app-button \/>/)
  assert.doesNotMatch(team, /<install-app-button \/>/)
  assert.match(personal, /class="personal-app notranslate" lang="zh-CN" translate="no"/)
  assert.match(team, /class="maintenance-shell notranslate" lang="zh-CN" translate="no"/)
  assert.doesNotMatch(personal, /personal-context/)
})

test('Codex integration exposes one-time read tokens and SSO-only operation approval', () => {
  const integrations = source('../src/views/CodexIntegrations.vue')
  const operation = source('../src/views/CodexOperation.vue')
  const router = source('../src/personal/router.js')
  const api = source('../src/api/client.js')
  const management = source('../src/views/About.vue')

  assert.match(router, /\/integrations\/codex\/operations\/:operationId/)
  assert.match(integrations, /密钥只显示一次/)
  assert.match(integrations, /WXY LAB Hardware · ChatGPT 接入/)
  assert.match(integrations, /完整读取个人业务库并提交无副作用草案/)
  assert.match(integrations, /listCodexTokens/)
  assert.match(integrations, /revokeCodexToken/)
  assert.match(operation, /批准并执行/)
  assert.match(operation, /必须输入：批准执行/)
  assert.match(operation, /申请撤销/)
  assert.match(operation, /目标状态变化后本单会拒绝执行/)
  assert.match(api, /approveCodexOperation/)
  assert.match(api, /requestCodexOperationUndo/)
  assert.match(management, /管理 ChatGPT 接入/)
})

test('management cards use a compact desktop grid without oversized empty rows', () => {
  const management = source('../src/views/About.vue')

  assert.match(management, /\.management-grid > \.panel:not\(\.danger-panel\)\s*\{\s*min-height:\s*0;/s)
  assert.match(management, /\.codex-panel\s*\{\s*grid-column:\s*span 2;/s)
  assert.match(management, /\.danger-panel\s*\{\s*grid-column:\s*auto;/s)
  assert.doesNotMatch(management, /min-height:\s*420px/)
})

test('programmatic Element Plus feedback imports its component styles', () => {
  const elementApi = source('../src/shared/elementApi.js')

  assert.match(elementApi, /element-plus\/es\/components\/message\/style\/css/)
  assert.match(elementApi, /element-plus\/es\/components\/message-box\/style\/css/)
  assert.match(elementApi, /element-plus\/es\/components\/notification\/style\/css/)
})

test('mobile bottom navigation distributes visible items evenly', () => {
  const personal = source('../src/personal/App.vue')
  const team = source('../src/team/styles.css')

  for (const text of [personal, team]) {
    assert.match(text, /display: flex/)
    assert.match(text, /justify-content: space-between/)
    assert.match(text, /flex: 1 1 0/)
    assert.match(text, /width: min\(100% - 20px, 520px\)/)
    assert.match(text, /border-radius: 22px/)
    assert.match(text, /border-radius: 16px/)
    assert.match(text, /linear-gradient\(180deg, #fff7ed, #ffedd5\)/)
    assert.match(text, /transition: color \.18s ease, background-color \.18s ease, transform \.18s ease/)
    assert.doesNotMatch(text, /grid-template-columns: repeat\(5, minmax\(0, 1fr\)\)/)
  }
})

test('team library cache failures do not turn successful API data into load errors', () => {
  const libraries = source('../src/team/views/Libraries.vue')
  assert.match(libraries, /const onlineLibraries = await listLibraries\(\)/)
  assert.match(libraries, /libraries\.value = onlineLibraries/)
  assert.match(libraries, /void writeSnapshot/)

  const cache = source('../src/team/cache.js')
  assert.match(cache, /catch \{\s+return false/)
  assert.match(cache, /catch \{\s+return null/)
})

test('team markers use eight fixed color presets without a color picker', () => {
  const components = source('../src/team/views/Components.vue')
  assert.doesNotMatch(components, /el-color-picker/)
  assert.match(components, /marker-color-presets/)
  assert.match(components, /TEAM_MARKER_COLORS/)

  const colors = source('../src/shared/markerColors.js')
  assert.equal((colors.match(/label:/g) || []).length, 8)
})

test('personal and team button layouts remove duplicate adjacent margins', () => {
  const personalStyles = source('../src/styles/main.css')
  assert.match(personalStyles, /\.toolbar,[\s\S]*\.el-button \+ \.el-button \{\s+margin-left: 0;/)
  assert.match(personalStyles, /\.toolbar \.el-button \{[\s\S]*margin-left: 0 !important;/)

  const teamStyles = source('../src/team/styles.css')
  assert.match(teamStyles, /\.team-toolbar \.el-button \+ \.el-button/)
  assert.match(teamStyles, /margin-left: 0;/)
})

test('personal navigation uses the team-style responsive shell without a sidebar', () => {
  const personal = source('../src/personal/App.vue')
  assert.match(personal, /class="personal-header"/)
  assert.match(personal, /class="personal-desktop-nav"/)
  assert.match(personal, /class="personal-mobile-nav"/)
  const mobileNavigation = personal.match(/<nav class="personal-mobile-nav"[\s\S]*?<\/nav>/)?.[0] || ''
  assert.equal((mobileNavigation.match(/<router-link/g) || []).length, 5)
  assert.doesNotMatch(mobileNavigation, /to="\/coverage"/)
  const management = source('../src/views/About.vue')
  assert.match(management, /class="page management-page"/)
  assert.doesNotMatch(management, /more-shortcuts/)
  assert.doesNotMatch(management, /to="\/coverage"/)
  assert.doesNotMatch(management, /to="\/purchases"/)
  assert.doesNotMatch(management, /to="\/risks"/)
  assert.match(personal, /cw-app-embedded/)
  assert.doesNotMatch(personal, /<el-aside/)
})

test('EDA mobile metrics use an isolated aligned two-column layout', () => {
  const eda = source('../src/shared/views/EdaLibrary.vue')
  assert.match(eda, /class="eda-metric-grid"/)
  assert.match(eda, /\.eda-metric-grid \{ grid-template-columns: repeat\(2, minmax\(0, 1fr\)\); \}/)
  assert.match(eda, /\.eda-metric-grid article:last-child \{ grid-column: 1 \/ -1; \}/)
  assert.doesNotMatch(eda, /class="metric-grid"/)
})

test('shared app bridge exposes auth scan NFC and account hooks', () => {
  const bridge = source('../src/shared/appBridge.js')
  assert.match(bridge, /window\.ComponentWarehouseBridge/)
  assert.match(bridge, /receiveAuthSession/)
  assert.match(bridge, /openAccountSettings/)
  assert.match(bridge, /requestScan/)
  assert.match(bridge, /receiveNfc/)

  const personal = source('../src/personal/App.vue')
  const team = source('../src/team/App.vue')
  assert.match(personal, /cw-native-auth-session/)
  assert.doesNotMatch(team, /cw-native-auth-session/)
})

test('personal and team component pages share real-time multi QR scanning', () => {
  const scanner = source('../src/shared/components/MultiQrScanner.vue')
  assert.match(scanner, /BarcodeDetector/)
  assert.match(scanner, /BrowserQRCodeReader/)
  assert.match(scanner, /multiple: true/)
  assert.match(scanner, /maxCodes/)
  assert.match(scanner, /scheduleResolve/)
  assert.match(scanner, /expected_mismatch/)
  assert.match(scanner, /class="scan-box"/)
  assert.match(scanner, /rememberDetections/)
  assert.match(scanner, /点击下方结果再进入详情/)
  assert.match(scanner, /@click="item.component && \$emit\('select', item.component\)"/)
  assert.match(scanner, /componentDisplaySubtitle/)
  assert.match(scanner, /currentBoxes/)
  assert.match(scanner, /currentVideoDisplayBox/)
  assert.match(scanner, /contentWidth/)
  assert.match(scanner, /watch\(expectedCode, \(\) => \{\s+clearCodes\(\)/)
  assert.match(scanner, /object-fit: contain/)
  assert.match(scanner, /objectFit === 'cover'/)
  assert.match(scanner, /object-fit: cover/)
  assert.match(scanner, /aspectRatio: \{ ideal: isMobileViewport\(\) \? 3 \/ 4 : 4 \/ 3 \}/)
  assert.match(scanner, /modal-class="scanner-overlay"/)
  assert.match(scanner, /body-class="scanner-dialog-body"/)
  assert.match(scanner, /width: min\(760px, calc\(100vw - 28px\)\) !important/)
  assert.match(scanner, /width: min\(520px, calc\(100vw - 16px\)\) !important/)
  assert.match(scanner, /height: min\(760px, calc\(100dvh - 28px\)\)/)
  assert.match(scanner, /\.scanner-overlay \.el-overlay-dialog/)
  assert.match(scanner, /box-sizing: border-box/)
  assert.match(scanner, /justify-content: center/)
  assert.match(scanner, /overflow: hidden/)
  assert.match(scanner, /--scanner-mobile-viewfinder-height: clamp\(190px, 34dvh, 320px\)/)
  assert.match(scanner, /calc\(var\(--scanner-mobile-viewfinder-height\) \* 3 \/ 4\)/)
  assert.match(scanner, /overscroll-behavior: contain/)
  assert.match(scanner, /grid-template-rows: max-content minmax\(0, 1fr\)/)
  assert.match(scanner, /\.scanner-overlay \.scanner-dialog-body/)
  assert.match(scanner, /flex: 1 1 0/)
  assert.match(scanner, /-webkit-overflow-scrolling: touch/)
  assert.match(scanner, /touch-action: pan-y/)
  assert.match(scanner, /aspect-ratio: 3 \/ 4/)
  assert.match(scanner, /height: calc\(100dvh - 16px\)/)
  assert.match(scanner, /initialExpectedCode/)
  assert.match(scanner, /initialExpectedLabel/)
  assert.match(scanner, /resolveInBatches/)
  assert.match(scanner, /const batchSize = 50/)
  assert.match(scanner, /tone: isExpected \? 'target' : 'scanned'/)
  assert.match(scanner, /\.scan-box\.scanned/)
  assert.match(scanner, /scanner-candidate-popper/)
  assert.match(scanner, /signalDetected/)
  assert.match(scanner, /maxCodes: \{ type: Number, default: 200 \}/)
  assert.match(scanner, /retainedCodeLimit/)
  assert.match(scanner, /droppedCodeCount/)
  assert.match(scanner, /列表保留最近/)
  assert.match(scanner, /navigator\.vibrate\?\.\(\[16, 28, 18\]\)/)
  assert.match(scanner, /navigator\.vibrate\?\.\(\[34, 42, 58, 36, 34\]\)/)
  assert.doesNotMatch(scanner, /非目标/)
  assert.doesNotMatch(scanner, /0 0 0 999px/)
  assert.doesNotMatch(scanner, /object-fit: fill/)
  assert.doesNotMatch(scanner, /aspect-ratio: 16 \/ 10/)
  assert.doesNotMatch(scanner, /calc\(42dvh \* 3 \/ 4\)/)
  assert.doesNotMatch(scanner, /next\.length >= props\.maxCodes/)
  assert.doesNotMatch(scanner, /window\.setTimeout\(\(\) => emit\('select'/)
  assert.match(scanner, /<details class="expected-picker">/)
  assert.doesNotMatch(scanner, /manualInput/)
  assert.doesNotMatch(scanner, /也可直接粘贴/)
  assert.match(scanner, /max-height: calc\(100dvh - 16px\)/)
  assert.match(scanner, /import\('@zxing\/browser'\)/)

  const personal = source('../src/views/Components.vue')
  const team = source('../src/team/views/Components.vue')
  assert.match(personal, /<multi-qr-scanner/)
  assert.match(personal, /resolvePersonalScanBatch/)
  assert.match(personal, /扫码定位此器件/)
  assert.match(personal, /scannerTarget/)
  assert.match(personal, /initial-expected-code/)
  assert.match(team, /<multi-qr-scanner/)
  assert.match(team, /resolveTeamScanBatch/)
  assert.match(team, /扫码定位此器件/)
  assert.match(team, /scannerTarget/)
  assert.match(team, /initial-expected-code/)
})

test('component lists page by complete categories and never slice a category', () => {
  const personal = source('../src/views/Components.vue')
  const team = source('../src/team/views/Components.vue')
  assert.match(personal, /autoLoadSentinel/)
  assert.match(personal, /IntersectionObserver/)
  assert.match(personal, /继续下滑自动加载/)
  assert.match(personal, /categoryPaging\.pageSize/)
  assert.match(team, /autoLoadSentinel/)
  assert.match(team, /IntersectionObserver/)
  assert.match(team, /继续下滑自动加载/)
  assert.match(team, /categoryPaging\.pageSize/)
  assert.doesNotMatch(team, /\.slice\([^)]*pageSize/)
})

test('public component page only uses safe identity fields and permission context', () => {
  const page = source('../src/views/PublicComponent.vue')
  assert.match(page, /getComponentAccessContext/)
  assert.match(page, /在个人版中管理/)
  assert.match(page, /不公开库存、位置、人员、团队或备注/)
  assert.doesNotMatch(page, /component\.quantity/)
  assert.doesNotMatch(page, /component\.location/)
})

test('personal and team expose the same engineering workflow pages', () => {
  const personalRouter = source('../src/personal/router.js')
  const teamRouter = source('../src/team/router.js')
  for (const page of ['eda', 'purchases', 'risks']) {
    assert.match(personalRouter, new RegExp(`/${page}`))
    assert.match(teamRouter, new RegExp(`/${page}`))
  }
  assert.match(teamRouter, /team-projects/)
  const eda = source('../src/shared/views/EdaLibrary.vue')
  assert.match(eda, /AD 元件库与工程资料/)
  assert.match(eda, /上传资料/)
  assert.match(eda, /关联元件/)
  assert.match(eda, /检查并发布/)
  assert.match(eda, /WXYLAB-AD-Sync-latest-win-x64\.zip/)
  assert.match(personalRouter, /eda-guide/)
  assert.match(teamRouter, /eda-guide/)
  assert.match(personalRouter, /manual/)
  assert.match(teamRouter, /manual/)
  assert.match(source('../src/shared/views/Purchases.vue'), /采购与到货入库/)
  assert.match(source('../src/shared/views/Risks.vue'), /风险检查/)
})

test('mobile navigation and EDA records stay in one responsive row', () => {
  const teamStyles = source('../src/team/styles.css')
  const eda = source('../src/shared/views/EdaLibrary.vue')
  assert.match(teamStyles, /display: flex/)
  assert.match(teamStyles, /flex: 1 1 0/)
  assert.doesNotMatch(teamStyles, /grid-template-columns: repeat\(5, minmax\(0, 1fr\)\)/)
  assert.match(eda, /class="eda-mobile-list"/)
  assert.match(eda, /class="eda-desktop-table"/)
  assert.match(eda, /@media \(max-width: 680px\)/)
})

test('management page keeps critical maintenance and removes category prefix clutter', () => {
  const about = source('../src/views/About.vue')
  const client = source('../src/api/client.js')
  assert.match(about, /<h1 class="page-title">管理<\/h1>/)
  assert.match(about, /导入批次/)
  assert.match(about, /AI 维护/)
  assert.match(about, /数据备份/)
  assert.match(about, /操作记录/)
  assert.match(about, /清库重录/)
  assert.match(about, /用户统计/)
  assert.match(about, /getAdminUsageDashboard/)
  assert.doesNotMatch(about, /类别与器件编号/)
  assert.doesNotMatch(about, /订单中已有明确类别时优先采用订单类别/)
  assert.doesNotMatch(about, /getCategories/)
  assert.doesNotMatch(about, /saveCategoryPrefix/)
  assert.doesNotMatch(client, /updateCategoryPrefix/)
})

test('label export is fixed to A4 40-grid paper with local calibration settings', () => {
  const dialog = source('../src/shared/components/LabelExportDialog.vue')
  const labels = source('../../backend/app/labels.py')
  assert.match(dialog, /52\.5 × 29\.7 mm/)
  assert.match(dialog, /导出范围/)
  assert.doesNotMatch(dialog, /当前列表/)
  assert.match(dialog, /指定日期/)
  assert.match(dialog, /全部库存/)
  assert.match(dialog, /导入日期/)
  assert.match(dialog, /排除类别/)
  assert.match(dialog, /默认排除：开发板、连接件/)
  assert.match(dialog, /imported_range/)
  assert.match(dialog, /imported_from/)
  assert.match(dialog, /imported_to/)
  assert.match(dialog, /excluded_categories/)
  assert.match(dialog, /excluded_categories: \['开发板', '连接件'\]/)
  assert.match(dialog, /template-relation/)
  assert.match(dialog, /器件标签固定使用系统默认版式/)
  assert.match(dialog, /不会影响前面的器件标签样式/)
  assert.match(dialog, /会按顺序打印该模板里的全部样式/)
  assert.doesNotMatch(dialog, /器件模板/)
  assert.doesNotMatch(dialog, /custom_template_id/)
  assert.match(dialog, /附加标签/)
  assert.match(dialog, /custom_label_ids/)
  assert.match(dialog, /custom_label_copies/)
  assert.match(dialog, /custom_labels/)
  assert.match(dialog, /categoryOptions/)
  assert.match(dialog, /customLabelTemplates/)
  assert.match(dialog, /scopeChoices/)
  assert.match(dialog, /请选择要导出的导入日期范围/)
  assert.match(dialog, /el-select/)
  assert.match(dialog, /el-select__wrapper/)
  assert.match(dialog, /起始格号/)
  assert.match(dialog, /横向偏移/)
  assert.match(dialog, /纵向偏移/)
  assert.match(dialog, /安全边距/)
  assert.match(dialog, /safe_margin/)
  assert.doesNotMatch(dialog, /低内存打印/)
  assert.doesNotMatch(dialog, /printer_safe/)
  assert.match(dialog, /打印校准页/)
  assert.match(dialog, /localStorage/)
  assert.match(dialog, /el-date-editor/)
  assert.match(dialog, /border-radius: var\(--cw-radius-control\)/)
  assert.match(labels, /class="label-frame"/)
  assert.match(labels, /class="label-logo"/)
  assert.match(labels, /LABEL_LOGO_URL = "\/component-warehouse\/api\/assets\/brand-logo-label\.png\?v=20260702b"/)
  assert.match(labels, /<img class="label-logo"/)
  assert.doesNotMatch(labels, /label-logo-text/)
  assert.doesNotMatch(labels, /printer_safe/)
  assert.match(labels, /class="label-print-meta"/)
  assert.match(labels, /class="label-stock-meta"/)
  assert.match(labels, /P:%Y-%m-%d %H:%M/)
  assert.match(labels, /qr_png_data_uri/)
  assert.match(labels, /PyPNGImage/)
  assert.match(labels, /入库 \{stocked\}/)
  assert.match(labels, /label_padding = "2\.15mm 2\.15mm"/)
  assert.match(labels, /outer_x_padding_value = 4\.8 if safe_margin else 3\.6/)
  assert.match(labels, /outer_x_padding = f"\{outer_x_padding_value:\.1f\}mm"/)
  assert.match(labels, /first_column_outer_left_padding = f"\{outer_x_padding_value \+ LABEL_FIRST_COLUMN_LEFT_SAFE_INSET_MM:\.2f\}mm"/)
  assert.match(labels, /outer_y_padding_value = 3\.4 if safe_margin else 2\.7/)
  assert.match(labels, /outer_y_padding = f"\{outer_y_padding_value:\.1f\}mm"/)
  assert.match(labels, /\.label-card:nth-child\(4n\+1\) \{\{ padding-left: \{first_column_outer_left_padding\}; \}\}/)
  assert.match(labels, /\.label-card:nth-child\(4n\) \{\{ padding-right: \{outer_x_padding\}; \}\}/)
  assert.match(labels, /grid-template-columns: 13\.4mm minmax\(0, 1fr\)/)
  assert.match(labels, /component_padding = "2\.15mm 1\.55mm 1\.95mm 2\.05mm"/)
  assert.match(labels, /component_padding = "2\.15mm 1\.55mm 1\.95mm 2\.05mm" if safe_margin else "1\.9mm 1\.3mm 1\.75mm 1\.75mm"/)
  assert.match(labels, /\.label-card:nth-child\(4n\+1\) \.component-frame/)
  assert.match(labels, /first_column_padding = "2\.6mm"/)
  assert.match(labels, /first_column_right = "1\.25mm"/)
  assert.match(labels, /label-copy-header/)
  assert.match(labels, /dingtalk_print_text_markup\(code, "label-code", 24\)/)
  assert.match(labels, /\.dingtalk-print-text/)
  assert.doesNotMatch(labels, /\.label-code-svg/)
  assert.doesNotMatch(labels, /background: url\("\{logo_uri\}"\)/)
  assert.match(labels, /print-color-adjust: exact/)
  assert.match(labels, /RASTER_SCALE = 2\.15/)
  assert.match(labels, /window\.__cwRasterizeLabels/)
  assert.match(labels, /raster-sheet/)
  assert.match(labels, /canvas\.toDataURL\('image\/png'\)/)
  assert.doesNotMatch(labels, /label-title-svg/)
  assert.match(labels, /aspect-ratio: 1 \/ 1/)
  assert.doesNotMatch(labels, /15\.45mm/)
  assert.match(labels, /border: \.18mm solid #cbd5e1/)
  assert.match(labels, /border-radius: 2mm/)
  assert.doesNotMatch(labels, /border: 0; border-radius: 0/)

  const personal = source('../src/views/Components.vue')
  const team = source('../src/team/views/Components.vue')
  assert.match(personal, /:category-options="categories"/)
  assert.match(personal, /:custom-label-templates="customLabels"/)
  assert.match(team, /teamLabelScopeOptions/)
  assert.match(team, /:scope-options="teamLabelScopeOptions"/)
  assert.match(team, /:category-options="categoryOptions"/)
  assert.match(team, /:custom-label-templates="customLabels"/)
  assert.match(personal, /router\.push\(\{ name: 'custom-labels' \}\)/)
  assert.match(team, /router\.push\(\{ name: 'team-custom-labels'/)
  const personalRouter = source('../src/personal/router.js')
  const teamRouter = source('../src/team/router.js')
  const personalLabelPage = source('../src/views/CustomLabels.vue')
  const teamLabelPage = source('../src/team/views/CustomLabels.vue')
  assert.match(personalRouter, /name: 'custom-labels'/)
  assert.match(teamRouter, /name: 'team-custom-labels'/)
  assert.match(personalLabelPage, /standalone/)
  assert.match(teamLabelPage, /standalone/)
  const customLabelDialog = source('../src/shared/components/CustomLabelDialog.vue')
  const personalApi = source('../src/api/client.js')
  const teamApi = source('../src/team/api.js')
  assert.match(customLabelDialog, /实时预览/)
  assert.match(customLabelDialog, /X\/Y 是位置，宽度\/高度是大小/)
  assert.match(customLabelDialog, /分类预设/)
  assert.match(customLabelDialog, /案例模板/)
  assert.match(customLabelDialog, /样式案例/)
  assert.match(customLabelDialog, /当前模板内样式/)
  assert.match(customLabelDialog, /品牌 Logo/)
  assert.match(customLabelDialog, /show_logo: true/)
  assert.match(customLabelDialog, /fontOptions/)
  assert.match(customLabelDialog, /得意黑/)
  assert.match(customLabelDialog, /钉钉进步体/)
  assert.match(customLabelDialog, /MiSans/)
  assert.match(customLabelDialog, /font_family/)
  assert.match(customLabelDialog, /ensurePreviewFonts/)
  assert.match(customLabelDialog, /FONT_PREVIEW_SCALE/)
  assert.match(customLabelDialog, /fieldPreviewValues/)
  assert.match(customLabelDialog, /withoutDuplicatePrintDate/)
  assert.match(customLabelDialog, /addField\('package', '封装 '\)/)
  assert.match(customLabelDialog, /元素对齐/)
  assert.match(customLabelDialog, /文字对齐/)
  assert.match(customLabelDialog, /alignElement/)
  assert.match(customLabelDialog, /snapElementBox/)
  assert.match(customLabelDialog, /SNAP_THRESHOLD_MM/)
  assert.match(customLabelDialog, /snapGuides/)
  assert.match(customLabelDialog, /nextTextBox/)
  assert.match(customLabelDialog, /水平居中/)
  assert.match(customLabelDialog, /垂直居中/)
  assert.match(customLabelDialog, /templateExamples/)
  assert.match(customLabelDialog, /导入案例模板/)
  assert.match(customLabelDialog, /templateExamplesOpen/)
  assert.match(customLabelDialog, /分类料盒标签/)
  assert.match(customLabelDialog, /待盘点\/待确认标签/)
  assert.doesNotMatch(customLabelDialog, /大字料盒标签/)
  assert.doesNotMatch(customLabelDialog, /器件二维码标签/)
  assert.doesNotMatch(customLabelDialog, /component-qr/)
  assert.doesNotMatch(customLabelDialog, /dense-component/)
  assert.doesNotMatch(customLabelDialog, /style-qr/)
  assert.doesNotMatch(customLabelDialog, /addQr/)
  assert.doesNotMatch(customLabelDialog, /qr-token/)
  assert.match(customLabelDialog, /styleExamples/)
  assert.match(customLabelDialog, /elementsForTemplateExample/)
  assert.match(customLabelDialog, /standardCategoryElements/)
  assert.match(customLabelDialog, /standard_category_group/)
  assert.match(customLabelDialog, /category_name/)
  assert.match(customLabelDialog, /categorySummaries/)
  assert.match(customLabelDialog, /activeStandardCategorySummary/)
  assert.match(customLabelDialog, /当前库里暂无此分类器件，导出时不生成/)
  assert.match(customLabelDialog, /modelSummaryCategories/)
  assert.match(customLabelDialog, /型号/)
  assert.match(customLabelDialog, /font_family: 'dingtalk'/)
  assert.doesNotMatch(customLabelDialog, /field: 'print_date'/)
  assert.doesNotMatch(customLabelDialog, /打印 ', x_mm/)
  assert.doesNotMatch(customLabelDialog, /⚡|🔋|🛡|⛓/)
  assert.doesNotMatch(customLabelDialog, /preset\.color/)
  assert.match(customLabelDialog, /startElementDrag/)
  assert.match(customLabelDialog, /startElementResize/)
  assert.match(customLabelDialog, /activeStyleId/)
  assert.match(customLabelDialog, /queueAssetPreview/)
  assert.match(customLabelDialog, /retryAssetPreview/)
  assert.match(customLabelDialog, /styles/)
  assert.match(customLabelDialog, /first_stocked_at/)
  assert.match(customLabelDialog, /categoryPresets/)
  assert.match(customLabelDialog, /X 位置 mm/)
  assert.match(customLabelDialog, /宽度 mm/)
  assert.match(customLabelDialog, /boxValue/)
  assert.match(customLabelDialog, /setBoxValue/)
  assert.match(customLabelDialog, /:controls="false"/)
  assert.match(customLabelDialog, /prepareAssetFile/)
  assert.match(customLabelDialog, /canvas\.toBlob/)
  assert.match(customLabelDialog, /URL\.createObjectURL/)
  assert.match(customLabelDialog, /loadAsset/)
  assert.match(personalLabelPage, /:load-asset="loadPersonalCustomLabelAsset"/)
  assert.match(personalLabelPage, /:category-summaries="categorySummaries"/)
  assert.match(personalApi, /getCustomLabelCategorySummary/)
  assert.match(teamLabelPage, /:load-asset="loadTeamCustomLabelFile"/)
  assert.match(teamLabelPage, /:category-summaries="categorySummaries"/)
  assert.match(teamApi, /getTeamCustomLabelCategorySummary/)
  assert.match(personalApi, /getCustomLabelAssetBlob/)
  assert.match(teamApi, /getTeamCustomLabelAssetBlob/)
})

test('custom label fonts are bundled for preview and print', () => {
  assert.equal(existsSync(new URL('../public/fonts/deyi/SmileySans-Oblique.woff2', import.meta.url)), true)
  assert.equal(existsSync(new URL('../public/fonts/dingtalk/font.css', import.meta.url)), true)
  assert.equal(existsSync(new URL('../public/fonts/misans/MiSans.min.css', import.meta.url)), true)
  const backendLabels = readFileSync(new URL('../../backend/app/labels.py', import.meta.url), 'utf8')
  assert.match(backendLabels, /custom_font_face_css/)
  assert.doesNotMatch(backendLabels, /data:font\/woff2;base64/)
  assert.match(backendLabels, /FONT_ASSET_WEB_BASE/)
  assert.match(backendLabels, /SmileySans-Oblique\.woff2/)
  assert.match(backendLabels, /DingTalk JinBuTi/)
  assert.match(backendLabels, /MiSans/)
})

test('personal component page keeps creation methods in the unified workspace', () => {
  const page = source('../src/views/Components.vue')
  const workspace = source('../src/components/inventory/ComponentCreateWorkspace.vue')
  assert.match(page, /class="toolbar compact-toolbar"/)
  assert.match(page, /<el-button type="primary" :icon="Plus" @click="openCreate">新增元器件<\/el-button>/)
  assert.match(page, /openScanner\(\)">扫码查找/)
  assert.match(page, /<el-popover[\s\S]*更多操作[\s\S]*导出 ID 表[\s\S]*导出库存 XLSX[\s\S]*导出标签\/PDF/)
  assert.match(page, /:lcsc-order-upload="handleExcelUpload"/)
  assert.match(page, /:image-upload="handleImageUpload"/)
  assert.match(page, /:external-order-upload="handleExternalOrderUpload"/)
  assert.match(workspace, /立创订单/)
  assert.match(workspace, /购物平台截图/)
  assert.match(workspace, /其他平台订单/)
  assert.doesNotMatch(page, /导出全部标签/)
  assert.doesNotMatch(page, /exportAllLabels/)
})

test('component cards and list surfaces use shared rounded rectangle radii', () => {
  const styles = source('../src/styles/main.css')
  const card = source('../src/components/inventory/InventoryComponentCard.vue')
  const page = source('../src/views/Components.vue')
  const personalApp = source('../src/personal/App.vue')
  const teamComponents = source('../src/team/views/Components.vue')
  assert.match(styles, /--cw-radius-card: 16px/)
  assert.match(styles, /--cw-radius-control: 16px/)
  assert.match(styles, /--cw-radius-chip: 999px/)
  assert.match(styles, /\.el-table \{[\s\S]*overflow: hidden/)
  assert.match(styles, /\.el-dropdown-menu__item,[\s\S]*border-radius: var\(--cw-radius-control\)/)
  assert.match(card, /min-height: 218px/)
  assert.match(card, /padding: 11px/)
  assert.match(card, /border-radius: var\(--cw-radius-card\)/)
  assert.match(card, /\.actions :deep\(\.el-button\)[\s\S]*border-radius: var\(--cw-radius-control\)/)
  assert.match(page, /grid-template-columns: repeat\(auto-fill, minmax\(370px, 1fr\)\)/)
  assert.match(teamComponents, /grid-template-columns: repeat\(auto-fill, minmax\(370px, 1fr\)\)/)
  assert.match(personalApp, /width: min\(1560px, calc\(100vw - 32px\)\)/)
  assert.match(page, /border-radius: var\(--cw-radius-control\)/)
})

test('component cards distinguish consumable checkout from durable equipment loss', () => {
  const card = source('../src/components/inventory/InventoryComponentCard.vue')
  const personal = source('../src/views/Components.vue')
  const team = source('../src/team/views/Components.vue')
  const semantics = source('../src/shared/componentInventorySemantics.js')
  assert.match(card, /<slot name="stock-action"/)
  assert.match(card, /class="stock-summary"/)
  assert.match(card, /quantityCopy\.totalLabel/)
  assert.match(card, /quantityCopy\.availableLabel/)
  assert.match(semantics, /category === '设备'/)
  assert.match(semantics, /actionLabel: '占用 1 台'/)
  assert.match(semantics, /actionLabel: '领用 1 个'/)
  assert.match(semantics, /'运输中'/)
  assert.match(personal, /<template #stock-action>/)
  assert.match(personal, /inventoryQuantityCopy\(item\)\.actionLabel/)
  assert.match(personal, /quickConsumeIds\.has\(item\.id\)/)
  assert.match(personal, /reason_type: durable \? 'loss' : 'consume'/)
  assert.match(personal, /quickOccupancy\(item, 'occupy'\)/)
  assert.match(personal, /quickOccupancy\(item, 'release'\)/)
  assert.match(personal, /updateComponentOccupancy/)
  assert.match(personal, /正常使用、借出和归还不需要改库存/)
  assert.match(personal, /ui\.components\.quick_consume/)
  assert.match(personal, /ui\.components\.quick_loss/)
  assert.match(team, /<template #stock-action>/)
  assert.match(team, /readonly \|\| !row\.can_edit_quantity/)
  assert.match(team, /inventoryQuantityCopy\(row\)\.actionLabel/)
  assert.match(team, /reason_type: durable \? 'loss' : 'consume'/)
  assert.match(team, /quickOccupancy\(row, 'occupy'\)/)
  assert.match(team, /quickOccupancy\(row, 'release'\)/)
  assert.match(team, /updateTeamComponentOccupancy/)
  assert.match(team, /ui\.team_components\.quick_consume/)
  assert.match(team, /ui\.team_components\.quick_loss/)
})

test('personal navigation is compact and usage tracking is wired', () => {
  const personal = source('../src/personal/App.vue')
  const client = source('../src/api/client.js')
  const teamApi = source('../src/team/api.js')
  const teamApp = source('../src/team/App.vue')
  const tracker = source('../src/shared/usageTracker.js')
  const desktopNavigation = personal.match(/<nav class="personal-desktop-nav"[\s\S]*?<\/nav>/)?.[0] || ''
  assert.match(desktopNavigation, /to="\/components"/)
  assert.match(desktopNavigation, /to="\/coverage"/)
  assert.match(desktopNavigation, /to="\/projects"/)
  assert.match(desktopNavigation, /to="\/eda"/)
  assert.match(desktopNavigation, /to="\/about"/)
  assert.match(desktopNavigation, /<InfoFilled \/>管理<\/router-link>/)
  assert.doesNotMatch(desktopNavigation, /to="\/admin"/)
  assert.doesNotMatch(desktopNavigation, /to="\/purchases"/)
  assert.doesNotMatch(desktopNavigation, /to="\/risks"/)
  assert.match(personal, /trackUsage\(recordUsageEvent, 'ui\.nav\.click'/)
  assert.match(personal, /<back-to-top/)
  assert.match(personal, /ui\.back_to_top\.click/)
  assert.match(teamApp, /团队版暂停维护/)
  assert.match(teamApp, /现有数据不会删除/)
  assert.match(client, /post\('\/usage-events'/)
  assert.match(teamApi, /usage-events/)
  assert.doesNotMatch(teamApp, /recordTeamUsageEvent/)
  assert.match(tracker, /recentEvents/)
})

test('all app shells expose shared copyright footer with optional filing records', () => {
  const footer = source('../src/shared/components/AppFooter.vue')
  const branding = source('../src/shared/branding.js')
  const dockerfile = source('../Dockerfile')
  const compose = source('../../docker-compose.yml')
  const envExample = source('../../.env.example')
  const personal = source('../src/personal/App.vue')
  const team = source('../src/team/App.vue')
  const teamStyles = source('../src/team/styles.css')
  const manual = source('../src/shared/views/UserManual.vue')
  const manualMd = source('../src/shared/manuals/userManual.md')
  assert.match(footer, /COPYRIGHT_TEXT/)
  assert.match(footer, /ICP_RECORD_TEXT/)
  assert.match(footer, /PUBLIC_SECURITY_RECORD_TEXT/)
  assert.match(branding, /VITE_COPYRIGHT_TEXT/)
  assert.match(branding, /VITE_ICP_RECORD_TEXT/)
  assert.match(branding, /VITE_PUBLIC_SECURITY_RECORD_TEXT/)
  assert.match(branding, /冀ICP备2026009111号-1/)
  assert.match(branding, /冀公网安备13010402003414号/)
  assert.match(dockerfile, /ARG VITE_ICP_RECORD_TEXT/)
  assert.match(compose, /VITE_PUBLIC_SECURITY_RECORD_TEXT/)
  assert.match(compose, /冀ICP备2026009111号-1/)
  assert.match(compose, /冀公网安备13010402003414号/)
  assert.match(envExample, /WXY LAB deployment filing records/)
  assert.doesNotMatch(footer, /京ICP备|沪ICP备|粤ICP备/)
  assert.doesNotMatch(footer, /公网安备\d/)
  assert.match(personal, /<app-footer \/>/)
  assert.match(team, /<app-footer \/>/)
  assert.match(personal, /standalone-shell/)
  assert.match(personal, /grid-template-rows: minmax\(0, 1fr\) auto/)
  assert.match(team, /maintenance-shell/)
  assert.match(team, /grid-template-rows: 1fr auto/)
  assert.match(manual, /MarkdownIt/)
  assert.match(manual, /userManual\.md\?raw/)
  assert.match(manualMd, /个人版/)
  assert.match(manualMd, /团队版/)
  assert.match(manualMd, /标签打印/)
})

test('component detail lot form uses responsive rounded card layout', () => {
  const detail = source('../src/components/inventory/InventoryComponentDetail.vue')
  assert.match(detail, /repeat\(auto-fit, minmax\(132px, 1fr\)\)/)
  assert.match(detail, /sourceLabel = \(value\) =>/)
  assert.match(detail, /external_order: '外部'/)
  assert.match(detail, /purchase: '采购'/)
  assert.match(detail, /min-width: 0/)
})

test('manual component drawer renders the edit form even before a component is selected', () => {
  const page = source('../src/views/Components.vue')
  const workspace = source('../src/components/inventory/ComponentCreateWorkspace.vue')
  assert.match(page, /const drawerTitle = computed\(\(\) => \(selected\.value \?[\s\S]*: '新增元器件'\)\)/)
  const drawer = page.match(/<el-drawer[\s\S]*?<\/el-drawer>/)?.[0] || ''
  assert.match(drawer, /class="component-detail-drawer"/)
  assert.match(drawer, /modal-class="component-detail-overlay"/)
  assert.match(drawer, /size="min\(1040px, calc\(100vw - 40px\)\)"/)
  assert.match(drawer, /@opened="resetDetailDrawerScroll"/)
  assert.match(drawer, /<template v-if="selected">[\s\S]*inventory-component-detail/)
  assert.match(drawer, /<\/template>\s*<component-create-workspace/)
  assert.match(drawer, /<el-form v-else-if="editing"/)
  assert.match(drawer, /@add-lot="addInventoryLot"/)
  assert.match(drawer, /@ask-ai="askSelectedComponentAi"/)
  assert.match(workspace, /AI 描述新增/)
  assert.match(workspace, /AI 生成草稿/)
  assert.match(page, /completeFormWithAi/)
  assert.match(page, /aiComponentInfo/)
  assert.match(workspace, /名称或型号至少填写一项/)
  assert.match(page, /function resetDetailDrawerScroll\(\)/)
  assert.match(page, /component-detail-drawer\.el-drawer \.el-drawer__body/)
  assert.match(page, /border-radius: var\(--cw-radius-card\) 0 0 var\(--cw-radius-card\)/)
  assert.match(page, /selected\.value\?\.id \|\| 'create'/)
  assert.match(page, /compact-toolbar[\s\S]*grid-template-columns: 1fr 1fr/)
  assert.match(page, /filter-panel[\s\S]*grid-template-columns: 1fr 1fr/)
})

test('team manual add supports AI draft and mobile-first controls', () => {
  const page = source('../src/team/views/Components.vue')
  const api = source('../src/team/api.js')
  const schemas = source('../../backend/app/team_schemas.py')
  const backend = source('../../backend/app/team.py')
  assert.match(page, /AI 快速新增/)
  assert.match(page, /completeManualWithAi/)
  assert.match(page, /manualQuickPrompt/)
  assert.match(page, /必填：名称或型号、库存数量/)
  assert.match(api, /aiComponentInfo/)
  assert.match(schemas, /package: str \| None/)
  assert.match(schemas, /parameters: str \| None/)
  assert.match(backend, /package=str\(values\.get\("package"\)/)
  assert.match(page, /class="component-detail-drawer"/)
  assert.match(page, /@opened="resetDetailDrawerScroll"/)
  assert.match(page, /function resetDetailDrawerScroll\(\)/)
  assert.match(page, /selected\.value\?\.id \|\| ''/)
  assert.match(page, /border-radius: var\(--cw-radius-card\) 0 0 var\(--cw-radius-card\)/)
  assert.match(page, /@media \(max-width: 680px\)[\s\S]*team-toolbar \{ display: grid/)
})

test('personal and team share deterministic LCSC paste preview flow', () => {
  const shared = source('../src/shared/components/LcscPasteImport.vue')
  const personal = source('../src/views/Components.vue')
  const personalWorkspace = source('../src/components/inventory/ComponentCreateWorkspace.vue')
  const team = source('../src/team/views/Components.vue')
  const personalApi = source('../src/api/client.js')
  const teamApi = source('../src/team/api.js')
  assert.match(shared, /立创一键录入/)
  assert.match(shared, /C\\s\*\(\\d\{3,\}\)/)
  assert.match(shared, /requestSequence/)
  assert.match(shared, /requestController\?\.abort/)
  assert.match(shared, /立创官方/)
  assert.match(shared, /AI 联网补全/)
  assert.match(shared, /仅文本解析/)
  assert.match(shared, /response\.existing_component/)
  assert.match(personalWorkspace, /<lcsc-paste-import/)
  assert.match(personal, /<component-create-workspace/)
  assert.match(personal, /applyLcscDraft/)
  assert.match(personal, /openExistingLcscComponent/)
  assert.match(personal, /lastLcscDraft/)
  assert.match(team, /<lcsc-paste-import/)
  assert.match(team, /applyTeamLcscDraft/)
  assert.match(team, /reuseExistingLcscComponent/)
  assert.match(team, /lastTeamLcscDraft/)
  assert.match(personalApi, /components\/lcsc\/preview/)
  assert.match(teamApi, /components\/lcsc\/preview/)
})

test('personal create workspace uses a compact two-level card flow', () => {
  const workspace = source('../src/components/inventory/ComponentCreateWorkspace.vue')
  assert.match(workspace, /统一录入工作台/)
  assert.match(workspace, /method-card-grid/)
  assert.match(workspace, /立创复制录入/)
  assert.match(workspace, /AI 描述新增/)
  assert.match(workspace, /手动填写/)
  assert.match(workspace, /批量导入/)
  assert.match(workspace, /v-if="activeMethod === 'batch'"/)
  assert.match(workspace, /选择批量来源/)
  assert.match(workspace, /确认入库草稿/)
  assert.match(workspace, /器件信息/)
  assert.match(workspace, /库存与来源/)
  assert.match(workspace, /扩展资料/)
  assert.match(workspace, /el-collapse/)
  assert.match(workspace, /create-save-bar/)
  assert.match(workspace, /@media \(max-width: 620px\)[\s\S]*method-card-grid \{ grid-template-columns: 1fr 1fr/)
  assert.match(workspace, /@media \(max-width: 620px\)[\s\S]*field-grid, \.inventory-field-grid \{ grid-template-columns: 1fr/)
})

test('project workspace keeps primary actions visible and isolates archive in the more menu', () => {
  const page = source('../src/views/ProjectWorkspace.vue')
  assert.match(page, /新建项目/)
  assert.match(page, /导入 BOM/)
  assert.match(page, /添加物料/)
  assert.match(page, /新增实物板/)
  assert.match(page, /handleProjectCommand/)
  assert.match(page, /command="archive">归档项目/)
  assert.doesNotMatch(page, /公开项目/)
  assert.doesNotMatch(page, /生成采购计划/)
})

test('personal project V2 uses an overview plus UUID detail route and lifecycle version cost workspace', () => {
  const page = source('../src/views/ProjectWorkspace.vue')
  const router = source('../src/personal/router.js')
  const api = source('../src/api/client.js')
  assert.match(router, /path: '\/projects'[\s\S]*ProjectWorkspace/)
  assert.match(router, /path: '\/projects\/:projectId\(\[0-9a-fA-F-\]\{36\}\)'[\s\S]*name: 'project-detail'/)
  assert.match(router, /path: '\/projects\/:legacyPath\(\.\*\)\*'[\s\S]*redirect: '\/projects'/)
  assert.doesNotMatch(router, /PublicProject/)
  assert.match(page, /活跃项目[\s\S]*综合实际成本[\s\S]*未计价项/)
  assert.match(page, /状态分布[\s\S]*周成本趋势[\s\S]*直接费用构成/)
  assert.match(page, /概览[\s\S]*PCB 版本[\s\S]*BOM 与装配[\s\S]*成本[\s\S]*文件与风险/)
  assert.match(page, /一个入口管理项目阶段/)
  assert.match(page, /稳定编号不可修改/)
  assert.match(page, /项目时间线/)
  assert.match(page, /lifecycle-track/)
  assert.match(page, /实际立项日期/)
  assert.match(page, /创建时所在阶段/)
  assert.match(page, /逐个填写已到达节点的真实日期/)
  assert.match(page, /timeline_actual: '实际节点'/)
  assert.match(page, /lifecycleRange\(node\)/)
  assert.match(page, /createTimelineDates/)
  assert.match(page, /date-week-field/)
  assert.match(page, /weekBadge\(infoForm\.start_date\)/)
  assert.match(page, /projectDates/)
  assert.match(page, /periodWeekRange/)
  assert.match(page, /@media \(max-width: 680px\)[\s\S]*\.lifecycle-track \{ min-width: 0; grid-template-columns: 1fr/)
  assert.match(api, /\/project-workspace\/bootstrap/)
  assert.match(api, /\/project-workspace\/projects/)
  assert.match(api, /\/cost\/fill-unpriced/)
})

test('personal and team surfaces share a high-contrast material system with stable light loading states', () => {
  const personalMain = source('../src/personal/main.js')
  const teamMain = source('../src/team/main.js')
  const personalApp = source('../src/personal/App.vue')
  const teamApp = source('../src/team/App.vue')
  const indexHtml = source('../index.html')
  const theme = source('../src/styles/material-theme.css')
  const inventoryDashboard = source('../src/views/Dashboard.vue')
  const projectWorkspace = source('../src/views/ProjectWorkspace.vue')
  assert.match(personalMain, /material-theme\.css/)
  assert.match(teamMain, /material-theme\.css/)
  assert.match(theme, /--cw-bg: #f2f6f7/)
  assert.match(theme, /--cw-text: #102a32/)
  assert.match(theme, /--cw-muted: #52666f/)
  assert.match(theme, /--cw-accent: #006b78/)
  assert.match(theme, /--cw-copper: #b45a22/)
  assert.ok(contrastRatio('#102a32', '#ffffff') >= 7)
  assert.ok(contrastRatio('#52666f', '#ffffff') >= 4.5)
  assert.ok(contrastRatio('#006b78', '#ffffff') >= 4.5)
  assert.ok(contrastRatio('#b45a22', '#ffffff') >= 4.5)
  assert.match(theme, /:where\(#app\) :where\(\.glass-panel, \.panel/)
  assert.doesNotMatch(theme, /#app :is\(\.glass-panel, \.panel/)
  assert.match(theme, /\.el-loading-mask[\s\S]*rgba\(242, 246, 247, 0\.78\)/)
  assert.match(theme, /\.el-loading-spinner \.path[\s\S]*stroke: var\(--cw-accent\)/)
  assert.match(indexHtml, /theme-color" content="#f2f6f7"/)
  assert.match(indexHtml, /html, body, #app[\s\S]*background: #f2f6f7/)
  assert.match(personalApp, /boot-spinner[\s\S]*正在验证个人硬件研发工作台/)
  assert.match(teamApp, /maintenance-shell[\s\S]*团队版暂停维护/)
  assert.match(theme, /backdrop-filter: none !important/)
  assert.doesNotMatch(theme, /backdrop-filter: blur/)
  assert.match(theme, /\.el-table \.cell[\s\S]*text-overflow: ellipsis/)
  assert.match(theme, /\.el-dialog[\s\S]*max-width: calc\(100vw - 24px\)/)
  assert.match(theme, /\.el-tag__content[\s\S]*white-space: nowrap/)
  assert.match(inventoryDashboard, /primaryMetrics/)
  assert.match(inventoryDashboard, /importantCategories\.value\.slice\(0, 6\)/)
  assert.match(inventoryDashboard, /actionItems\.value\.slice\(0, 4\)/)
  assert.match(inventoryDashboard, /lowStockItems\.value\.slice\(0, 4\)/)
  assert.match(inventoryDashboard, /content-visibility: auto/)
  assert.match(inventoryDashboard, /contain-intrinsic-size/)
  assert.match(projectWorkspace, /workspace-loader/)
  assert.match(projectWorkspace, /background: #fff/)
  assert.doesNotMatch(projectWorkspace, /backdrop-filter/)
  assert.match(projectWorkspace, /text-overflow: ellipsis/)
  assert.match(projectWorkspace, /overflow-wrap: anywhere/)
  assert.match(projectWorkspace, /label-position="top"/)
  assert.match(projectWorkspace, /@media \(max-width: 680px\)/)
  assert.match(projectWorkspace, /prefers-reduced-motion/)
})

test('project V2 BOM uses explicit inventory selection and never treats missing prices as zero', () => {
  const page = source('../src/views/ProjectWorkspace.vue')
  const backend = source('../../backend/app/personal_projects_v2.py')
  assert.match(page, /库存元器件/)
  assert.match(page, /均价缺失，不按零元计算/)
  assert.match(page, /item\.unpriced \? '未计价'/)
  assert.match(backend, /unpriced_bom_items/)
  assert.match(backend, /average_unit_price is None/)
  assert.match(backend, /库存不足，本次未扣减/)
})

test('admin dashboard and login policy are wired', () => {
  const router = source('../src/personal/router.js')
  const app = source('../src/personal/App.vue')
  const about = source('../src/views/About.vue')
  const auth = source('../src/components/AuthPanel.vue')
  const api = source('../src/api/client.js')
  const backend = source('../../backend/app/main.py')
  const authBackend = source('../../backend/app/auth.py')
  assert.match(router, /path: '\/admin'/)
  assert.match(router, /redirect: '\/about'/)
  assert.doesNotMatch(app, /to="\/admin"/)
  assert.match(about, /isAdmin/)
  assert.match(about, /用户统计/)
  assert.match(about, /月活/)
  assert.match(about, /常用功能/)
  assert.match(about, /最近界面操作/)
  assert.match(api, /getAdminUsageDashboard/)
  assert.match(backend, /\/api\/admin\/usage-dashboard/)
  assert.match(backend, /monthly_active_users/)
  assert.match(authBackend, /ADMIN_PHONE_NUMBERS/)
  assert.match(auth, /使用条款/)
  assert.match(auth, /隐私协议/)
  assert.match(auth, /termsAccepted/)
  assert.match(auth, /cw_terms_accepted/)
})

test('legacy personal and public project entries resolve to the single workspace', () => {
  const router = source('../src/personal/router.js')
  assert.match(router, /\/projects\/:legacyPath/)
  assert.match(router, /\/public\/projects\/:legacyPath/)
  assert.doesNotMatch(router, /\.\.\/views\/Projects\.vue/)
  assert.doesNotMatch(router, /\.\.\/views\/PublicProject\.vue/)
})

test('project V2 risks and files are explicit workspace records', () => {
  const page = source('../src/views/ProjectWorkspace.vue')
  const api = source('../src/api/client.js')
  assert.match(page, /风险与待办/)
  assert.match(page, /添加项目风险/)
  assert.match(page, /工程文件/)
  assert.match(page, /单文件最大 20 MB/)
  assert.match(api, /uploadWorkspaceFile/)
  assert.match(api, /updateWorkspaceRisk/)
})

test('personal V2 BOM import is warehouse-code deterministic while team mapping remains unchanged', () => {
  const personal = source('../src/views/ProjectWorkspace.vue')
  const team = source('../src/team/views/Projects.vue')
  const mapping = source('../src/shared/components/BomFieldMappingDialog.vue')
  const backend = source('../../backend/app/personal_projects_v2.py')
  assert.match(personal, /accept="\.csv,\.xlsx,\.xlsm"/)
  assert.match(backend, /BOM 缺少仓库编号列/)
  assert.match(backend, /库存中未找到/)
  assert.match(team, /BomFieldMappingDialog/)
  assert.match(mapping, /Quantity \/ 数量/)
  assert.match(mapping, /系统仅按表头精确识别/)
})

test('personal V2 integrates the Gerber workbench into the current BOM workspace while team stays available', () => {
  const personal = source('../src/views/ProjectWorkspace.vue')
  const team = source('../src/team/views/Projects.vue')
  const workbench = source('../src/shared/components/AssemblyWorkbench.vue')
  assert.match(personal, /实物板/)
  assert.match(personal, /runPointAction/)
  assert.match(personal, /撤销报损/)
  assert.match(personal, /AssemblyWorkbench/)
  assert.match(personal, /workspace-version-id/)
  assert.match(workbench, /is-workspace/)
  assert.match(workbench, /制造资料与可视化装配/)
  assert.match(team, /AssemblyWorkbench/)
  assert.match(workbench, /上传 Gerber 制造包/)
  assert.match(workbench, /确认前不改变装配或库存/)
  assert.match(workbench, /顶面/)
  assert.match(workbench, /底面翻板视角/)
  assert.match(workbench, /板框/)
  assert.match(workbench, /铜层/)
  assert.match(workbench, /阻焊/)
  assert.match(workbench, /丝印/)
})

test('assembly workbench exposes safe tool modes navigation calibration and responsive mobile controls', () => {
  const workbench = source('../src/shared/components/AssemblyWorkbench.vue')
  assert.match(workbench, /value: 'select'.*label: '选择'/)
  assert.match(workbench, /value: 'solder'.*label: '焊接'/)
  assert.match(workbench, /value: 'loss'.*label: '报损'/)
  assert.match(workbench, /value: 'calibrate'.*label: '校准'/)
  assert.match(workbench, /event\.key\.toLowerCase\(\) === 'v'/)
  assert.match(workbench, /event\.key\.toLowerCase\(\) === 's'/)
  assert.match(workbench, /event\.key\.toLowerCase\(\) === 'l'/)
  assert.match(workbench, /event\.ctrlKey \|\| event\.metaKey/)
  assert.match(workbench, /@wheel\.prevent="handleWheel"/)
  assert.match(workbench, /startPan/)
  assert.match(workbench, /未定位托盘/)
  assert.match(workbench, /恢复当前位号解析值/)
  assert.match(workbench, /@media \(max-width: 720px\)/)
  assert.match(workbench, /补充报损原因/)
  assert.match(workbench, /公开装配简图/)
})

test('assembly API client keeps personal and team endpoint tails identical', () => {
  const api = source('../src/shared/engineeringApi.js')
  assert.match(api, /const projectBase/)
  assert.match(api, /fabrication-revisions/)
  assert.match(api, /assembly-view/)
  assert.match(api, /boards\/batch/)
  assert.match(api, /assembly-actions/)
  assert.match(api, /\/calibration/)
  assert.match(api, /\/placements\//)
})
