import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

function source(path) {
  return readFileSync(new URL(path, import.meta.url), 'utf8')
}

test('team detail keeps privileged actions in the three-dot menu', () => {
  const text = source('../src/team/views/Components.vue')
  assert.match(text, /<el-dropdown/)
  assert.match(text, /selected\.can_edit_quantity/)
  assert.match(text, /command="remove"/)
  assert.doesNotMatch(text, /<template #actions>[\s\S]{0,300}移出团队器件库/)
})

test('usage records are collapsed and lazy loaded', () => {
  const text = source('../src/components/inventory/InventoryComponentDetail.vue')
  assert.match(text, /usageExpanded/)
  assert.match(text, /emit\('load-usage', 20\)/)
  assert.match(text, /max-height: 360px/)
})

test('component detail exposes inventory lots and component-scoped AI question UI', () => {
  const text = source('../src/components/inventory/InventoryComponentDetail.vue')
  const page = source('../src/views/Components.vue')
  assert.match(text, /库存批次 \/ 采购渠道/)
  assert.match(text, /新增批次/)
  assert.match(text, /@click="\$emit\('consume-lot', lot\)"/)
  assert.match(text, /问这个元器件/)
  assert.match(text, /emit\('ask-ai', question\)/)
  assert.match(text, /packageTagStyle/)
  assert.match(page, /移除记录/)
  assert.match(page, /removeSelectedComponent/)
  assert.match(page, /不会释放或复用/)
  assert.match(page, /deleteComponent/)
})

test('PCB empty state is separate from request failure handling', () => {
  const text = source('../src/team/views/Pcbs.vue')
  assert.match(text, /暂无 PCB/)
  assert.match(text, /const libraryData = await getLibrary/)
  assert.match(text, /const pcbData = await listPcbs/)
})

test('hidden account tabs lazy-load captcha and errors are shown inline', () => {
  const auth = source('../src/components/AuthPanel.vue')
  assert.match(auth, /name="sms" lazy/)
  assert.match(auth, /name="register" lazy/)
  assert.match(auth, /name="reset" lazy/)
  assert.match(auth, /serviceError/)
  assert.doesNotMatch(auth, /errorMessage\(error, '操作失败'\)/)

  const account = source('../src/shared/components/AccountPopover.vue')
  assert.match(account, /name="password" lazy/)
  assert.match(account, /name="phone" lazy/)
  assert.match(account, /captchaError/)
  assert.match(account, /v-model:visible="popoverVisible"/)
  assert.match(account, /await nextTick\(\)/)
  assert.match(account, /append-to-body/)
  assert.match(account, /cw-open-account-settings/)
  assert.match(account, /fetchAccountProfile/)
  assert.match(account, /cw-account-popover/)
})

test('team library cache failures do not turn successful API data into load errors', () => {
  const libraries = source('../src/team/views/Libraries.vue')
  assert.match(libraries, /const onlineLibraries = await listLibraries\(\)/)
  assert.match(libraries, /libraries\.value = onlineLibraries/)
  assert.match(libraries, /void writeSnapshot/)

  const cache = source('../src/team/cache.js')
  assert.match(cache, /catch \{\s+return false/)
  assert.match(cache, /catch \{\s+return null/)
})

test('team markers use eight fixed color presets without a color picker', () => {
  const components = source('../src/team/views/Components.vue')
  assert.doesNotMatch(components, /el-color-picker/)
  assert.match(components, /marker-color-presets/)
  assert.match(components, /TEAM_MARKER_COLORS/)

  const colors = source('../src/shared/markerColors.js')
  assert.equal((colors.match(/label:/g) || []).length, 8)
})

test('personal and team button layouts remove duplicate adjacent margins', () => {
  const personalStyles = source('../src/styles/main.css')
  assert.match(personalStyles, /\.toolbar,[\s\S]*\.el-button \+ \.el-button \{\s+margin-left: 0;/)
  assert.match(personalStyles, /\.toolbar \.el-button \{[\s\S]*margin-left: 0 !important;/)

  const teamStyles = source('../src/team/styles.css')
  assert.match(teamStyles, /\.team-toolbar \.el-button \+ \.el-button/)
  assert.match(teamStyles, /margin-left: 0;/)
})

test('personal navigation uses the team-style responsive shell without a sidebar', () => {
  const personal = source('../src/personal/App.vue')
  assert.match(personal, /class="personal-header"/)
  assert.match(personal, /class="personal-desktop-nav"/)
  assert.match(personal, /class="personal-mobile-nav"/)
  const mobileNavigation = personal.match(/<nav class="personal-mobile-nav"[\s\S]*?<\/nav>/)?.[0] || ''
  assert.equal((mobileNavigation.match(/<router-link/g) || []).length, 5)
  assert.doesNotMatch(mobileNavigation, /to="\/coverage"/)
  const more = source('../src/views/About.vue')
  assert.match(more, /class="more-shortcuts"/)
  assert.match(more, /to="\/coverage"/)
  assert.match(more, /to="\/purchases"/)
  assert.match(more, /to="\/risks"/)
  assert.match(personal, /cw-app-embedded/)
  assert.doesNotMatch(personal, /<el-aside/)
})

test('EDA mobile metrics use an isolated aligned two-column layout', () => {
  const eda = source('../src/shared/views/EdaLibrary.vue')
  assert.match(eda, /class="eda-metric-grid"/)
  assert.match(eda, /\.eda-metric-grid \{ grid-template-columns: repeat\(2, minmax\(0, 1fr\)\); \}/)
  assert.match(eda, /\.eda-metric-grid article:last-child \{ grid-column: 1 \/ -1; \}/)
  assert.doesNotMatch(eda, /class="metric-grid"/)
})

test('shared app bridge exposes auth scan NFC and account hooks', () => {
  const bridge = source('../src/shared/appBridge.js')
  assert.match(bridge, /window\.ComponentWarehouseBridge/)
  assert.match(bridge, /receiveAuthSession/)
  assert.match(bridge, /openAccountSettings/)
  assert.match(bridge, /requestScan/)
  assert.match(bridge, /receiveNfc/)

  const personal = source('../src/personal/App.vue')
  const team = source('../src/team/App.vue')
  assert.match(personal, /cw-native-auth-session/)
  assert.match(team, /cw-native-auth-session/)
})

test('personal and team component pages share real-time multi QR scanning', () => {
  const scanner = source('../src/shared/components/MultiQrScanner.vue')
  assert.match(scanner, /BarcodeDetector/)
  assert.match(scanner, /BrowserQRCodeReader/)
  assert.match(scanner, /multiple: true/)
  assert.match(scanner, /maxCodes/)
  assert.match(scanner, /scheduleResolve/)
  assert.match(scanner, /expected_mismatch/)
  assert.match(scanner, /class="scan-box"/)
  assert.match(scanner, /rememberDetections/)
  assert.match(scanner, /点击下方结果再进入详情/)
  assert.match(scanner, /@click="item.component && \$emit\('select', item.component\)"/)
  assert.match(scanner, /componentDisplaySubtitle/)
  assert.match(scanner, /currentBoxes/)
  assert.match(scanner, /currentVideoDisplayBox/)
  assert.match(scanner, /contentWidth/)
  assert.match(scanner, /object-fit: contain/)
  assert.match(scanner, /objectFit === 'cover'/)
  assert.match(scanner, /object-fit: cover/)
  assert.match(scanner, /aspectRatio: \{ ideal: isMobileViewport\(\) \? 3 \/ 4 : 4 \/ 3 \}/)
  assert.match(scanner, /calc\(56dvh \* 3 \/ 4\)/)
  assert.match(scanner, /aspect-ratio: 3 \/ 4/)
  assert.match(scanner, /signalDetected/)
  assert.match(scanner, /maxCodes: \{ type: Number, default: 200 \}/)
  assert.match(scanner, /retainedCodeLimit/)
  assert.match(scanner, /droppedCodeCount/)
  assert.match(scanner, /列表保留最近/)
  assert.match(scanner, /navigator\.vibrate\?\.\(\[16, 28, 18\]\)/)
  assert.match(scanner, /navigator\.vibrate\?\.\(\[34, 42, 58, 36, 34\]\)/)
  assert.doesNotMatch(scanner, /非目标/)
  assert.doesNotMatch(scanner, /0 0 0 999px/)
  assert.doesNotMatch(scanner, /object-fit: fill/)
  assert.doesNotMatch(scanner, /aspect-ratio: 16 \/ 10/)
  assert.doesNotMatch(scanner, /next\.length >= props\.maxCodes/)
  assert.doesNotMatch(scanner, /window\.setTimeout\(\(\) => emit\('select'/)
  assert.match(scanner, /<details class="expected-picker">/)
  assert.match(scanner, /max-height: calc\(100dvh - 16px\)/)
  assert.match(scanner, /import\('@zxing\/browser'\)/)

  const personal = source('../src/views/Components.vue')
  const team = source('../src/team/views/Components.vue')
  assert.match(personal, /<multi-qr-scanner/)
  assert.match(personal, /resolvePersonalScanBatch/)
  assert.match(team, /<multi-qr-scanner/)
  assert.match(team, /resolveTeamScanBatch/)
})

test('component lists page by complete categories and never slice a category', () => {
  const personal = source('../src/views/Components.vue')
  const team = source('../src/team/views/Components.vue')
  assert.match(personal, /autoLoadSentinel/)
  assert.match(personal, /IntersectionObserver/)
  assert.match(personal, /继续下滑自动加载/)
  assert.match(personal, /categoryPaging\.pageSize/)
  assert.match(team, /autoLoadSentinel/)
  assert.match(team, /IntersectionObserver/)
  assert.match(team, /继续下滑自动加载/)
  assert.match(team, /categoryPaging\.pageSize/)
  assert.doesNotMatch(team, /\.slice\([^)]*pageSize/)
})

test('public component page only uses safe identity fields and permission context', () => {
  const page = source('../src/views/PublicComponent.vue')
  assert.match(page, /getComponentAccessContext/)
  assert.match(page, /在个人版中管理/)
  assert.match(page, /不公开库存、位置、人员、团队或备注/)
  assert.doesNotMatch(page, /component\.quantity/)
  assert.doesNotMatch(page, /component\.location/)
})

test('personal and team expose the same engineering workflow pages', () => {
  const personalRouter = source('../src/personal/router.js')
  const teamRouter = source('../src/team/router.js')
  for (const page of ['eda', 'purchases', 'risks']) {
    assert.match(personalRouter, new RegExp(`/${page}`))
    assert.match(teamRouter, new RegExp(`/${page}`))
  }
  assert.match(teamRouter, /team-projects/)
  const eda = source('../src/shared/views/EdaLibrary.vue')
  assert.match(eda, /AD 元件库与工程资料/)
  assert.match(eda, /上传资料/)
  assert.match(eda, /关联元件/)
  assert.match(eda, /检查并发布/)
  assert.match(eda, /ComponentWarehouse-AD-Sync-latest-win-x64\.zip/)
  assert.match(personalRouter, /eda-guide/)
  assert.match(teamRouter, /eda-guide/)
  assert.match(personalRouter, /manual/)
  assert.match(teamRouter, /manual/)
  assert.match(source('../src/shared/views/Purchases.vue'), /采购与到货入库/)
  assert.match(source('../src/shared/views/Risks.vue'), /风险检查/)
})

test('mobile navigation and EDA records stay in one responsive row', () => {
  const teamStyles = source('../src/team/styles.css')
  const eda = source('../src/shared/views/EdaLibrary.vue')
  assert.match(teamStyles, /grid-template-columns: repeat\(5, minmax\(0, 1fr\)\)/)
  assert.match(eda, /class="eda-mobile-list"/)
  assert.match(eda, /class="eda-desktop-table"/)
  assert.match(eda, /@media \(max-width: 680px\)/)
})

test('category prefixes are system managed and no longer editable', () => {
  const about = source('../src/views/About.vue')
  const client = source('../src/api/client.js')
  assert.match(about, /系统管理/)
  assert.match(about, /订单中已有明确类别时优先采用订单类别/)
  assert.doesNotMatch(about, /saveCategoryPrefix/)
  assert.doesNotMatch(client, /updateCategoryPrefix/)
})

test('label export is fixed to A4 40-grid paper with local calibration settings', () => {
  const dialog = source('../src/shared/components/LabelExportDialog.vue')
  const labels = source('../../backend/app/labels.py')
  assert.match(dialog, /52\.5 × 29\.7 mm/)
  assert.match(dialog, /导出范围/)
  assert.doesNotMatch(dialog, /当前列表/)
  assert.match(dialog, /指定日期/)
  assert.match(dialog, /全部库存/)
  assert.match(dialog, /导入日期/)
  assert.match(dialog, /排除类别/)
  assert.match(dialog, /例如：开发板、连接件/)
  assert.match(dialog, /imported_range/)
  assert.match(dialog, /imported_from/)
  assert.match(dialog, /imported_to/)
  assert.match(dialog, /excluded_categories/)
  assert.match(dialog, /excluded_categories: \['开发板'\]/)
  assert.match(dialog, /附加标签/)
  assert.match(dialog, /custom_label_ids/)
  assert.match(dialog, /custom_label_copies/)
  assert.match(dialog, /custom_labels/)
  assert.match(dialog, /categoryOptions/)
  assert.match(dialog, /customLabelTemplates/)
  assert.match(dialog, /scopeChoices/)
  assert.match(dialog, /请选择要导出的导入日期范围/)
  assert.match(dialog, /el-select/)
  assert.match(dialog, /el-select__wrapper/)
  assert.match(dialog, /起始格号/)
  assert.match(dialog, /横向偏移/)
  assert.match(dialog, /纵向偏移/)
  assert.match(dialog, /打印校准页/)
  assert.match(dialog, /localStorage/)
  assert.match(dialog, /el-date-editor/)
  assert.match(dialog, /border-radius: var\(--cw-radius-control\)/)
  assert.match(labels, /class="label-frame"/)
  assert.match(labels, /class="label-logo"/)
  assert.match(labels, /class="label-print-meta"/)
  assert.match(labels, /P:%Y-%m-%d %H:%M/)
  assert.match(labels, /padding: 1\.22mm 1\.32mm/)
  assert.match(labels, /grid-template-columns: 17mm minmax\(0, 1fr\)/)
  assert.match(labels, /padding: 1\.9mm 2\.2mm 1\.9mm 3\.7mm/)
  assert.match(labels, /\.label-card:nth-child\(4n\+1\) \.component-frame/)
  assert.match(labels, /padding-left: 5\.9mm/)
  assert.match(labels, /padding-right: \.95mm/)
  assert.match(labels, /aspect-ratio: 1 \/ 1/)
  assert.doesNotMatch(labels, /15\.45mm/)
  assert.match(labels, /border: \.18mm solid #cbd5e1/)
  assert.match(labels, /border-radius: 2mm/)
  assert.doesNotMatch(labels, /border: 0; border-radius: 0/)

  const personal = source('../src/views/Components.vue')
  const team = source('../src/team/views/Components.vue')
  assert.match(personal, /:category-options="categories"/)
  assert.match(personal, /:custom-label-templates="customLabels"/)
  assert.match(team, /teamLabelScopeOptions/)
  assert.match(team, /:scope-options="teamLabelScopeOptions"/)
  assert.match(team, /:category-options="categoryOptions"/)
  assert.match(team, /:custom-label-templates="customLabels"/)
  assert.match(personal, /<custom-label-dialog/)
  assert.match(team, /<custom-label-dialog/)
  const customLabelDialog = source('../src/shared/components/CustomLabelDialog.vue')
  const personalApi = source('../src/api/client.js')
  const teamApi = source('../src/team/api.js')
  assert.match(customLabelDialog, /实时预览/)
  assert.match(customLabelDialog, /X\/Y 是位置，宽度\/高度是大小/)
  assert.match(customLabelDialog, /X 位置/)
  assert.match(customLabelDialog, /宽度/)
  assert.match(customLabelDialog, /:controls="false"/)
  assert.match(customLabelDialog, /prepareAssetFile/)
  assert.match(customLabelDialog, /canvas\.toBlob/)
  assert.match(customLabelDialog, /URL\.createObjectURL/)
  assert.match(customLabelDialog, /loadAsset/)
  assert.match(personal, /:load-asset="loadPersonalCustomLabelAsset"/)
  assert.match(team, /:load-asset="loadTeamCustomLabelFile"/)
  assert.match(personalApi, /getCustomLabelAssetBlob/)
  assert.match(teamApi, /getTeamCustomLabelAssetBlob/)
})

test('personal component page keeps only common actions in the top toolbar', () => {
  const page = source('../src/views/Components.vue')
  assert.match(page, /class="toolbar compact-toolbar"/)
  assert.match(page, /<el-button type="primary" :icon="Plus" @click="openCreate">新增元器件<\/el-button>/)
  assert.match(page, /handleExcelUpload[\s\S]*导入立创订单/)
  assert.match(page, /scannerVisible = true">扫码查找/)
  assert.match(page, /<el-popover[\s\S]*更多操作[\s\S]*图片识别导入[\s\S]*导入外部订单[\s\S]*导出 ID 表[\s\S]*导出库存 XLSX[\s\S]*导出标签\/PDF/)
  assert.doesNotMatch(page, /导出全部标签/)
  assert.doesNotMatch(page, /exportAllLabels/)
})

test('component cards and list surfaces use shared rounded rectangle radii', () => {
  const styles = source('../src/styles/main.css')
  const card = source('../src/components/inventory/InventoryComponentCard.vue')
  const page = source('../src/views/Components.vue')
  const personalApp = source('../src/personal/App.vue')
  const teamComponents = source('../src/team/views/Components.vue')
  assert.match(styles, /--cw-radius-card: 16px/)
  assert.match(styles, /--cw-radius-control: 16px/)
  assert.match(styles, /--cw-radius-chip: 999px/)
  assert.match(styles, /\.el-table \{[\s\S]*overflow: hidden/)
  assert.match(styles, /\.el-dropdown-menu__item,[\s\S]*border-radius: var\(--cw-radius-control\)/)
  assert.match(card, /min-height: 218px/)
  assert.match(card, /padding: 11px/)
  assert.match(card, /border-radius: var\(--cw-radius-card\)/)
  assert.match(card, /\.actions :deep\(\.el-button\)[\s\S]*border-radius: var\(--cw-radius-control\)/)
  assert.match(page, /grid-template-columns: repeat\(auto-fill, minmax\(370px, 1fr\)\)/)
  assert.match(teamComponents, /grid-template-columns: repeat\(auto-fill, minmax\(370px, 1fr\)\)/)
  assert.match(personalApp, /width: min\(1560px, calc\(100vw - 32px\)\)/)
  assert.match(page, /border-radius: var\(--cw-radius-control\)/)
})

test('personal navigation is compact and usage tracking is wired', () => {
  const personal = source('../src/personal/App.vue')
  const client = source('../src/api/client.js')
  const teamApi = source('../src/team/api.js')
  const teamApp = source('../src/team/App.vue')
  const tracker = source('../src/shared/usageTracker.js')
  const desktopNavigation = personal.match(/<nav class="personal-desktop-nav"[\s\S]*?<\/nav>/)?.[0] || ''
  assert.match(desktopNavigation, /to="\/components"/)
  assert.match(desktopNavigation, /to="\/coverage"/)
  assert.match(desktopNavigation, /to="\/projects"/)
  assert.match(desktopNavigation, /to="\/eda"/)
  assert.match(desktopNavigation, /to="\/about"/)
  assert.doesNotMatch(desktopNavigation, /to="\/purchases"/)
  assert.doesNotMatch(desktopNavigation, /to="\/risks"/)
  assert.match(personal, /trackUsage\(recordUsageEvent, 'ui\.nav\.click'/)
  assert.match(personal, /<back-to-top/)
  assert.match(personal, /ui\.back_to_top\.click/)
  assert.match(teamApp, /<back-to-top/)
  assert.match(teamApp, /ui\.back_to_top\.click/)
  assert.match(client, /post\('\/usage-events'/)
  assert.match(teamApi, /usage-events/)
  assert.match(teamApp, /recordTeamUsageEvent/)
  assert.match(tracker, /recentEvents/)
})

test('all app shells expose shared copyright footer without filing numbers', () => {
  const footer = source('../src/shared/components/AppFooter.vue')
  const personal = source('../src/personal/App.vue')
  const team = source('../src/team/App.vue')
  const manual = source('../src/shared/views/UserManual.vue')
  const manualMd = source('../src/shared/manuals/userManual.md')
  assert.match(footer, /© 2026 Component Warehouse/)
  assert.doesNotMatch(footer, /ICP备/)
  assert.doesNotMatch(footer, /公网安备/)
  assert.doesNotMatch(footer, /beian\.mps\.gov\.cn/)
  assert.match(personal, /<app-footer \/>/)
  assert.match(team, /<app-footer \/>/)
  assert.match(personal, /standalone-shell/)
  assert.match(team, /team-standalone-shell/)
  assert.match(manual, /MarkdownIt/)
  assert.match(manual, /userManual\.md\?raw/)
  assert.match(manualMd, /个人版/)
  assert.match(manualMd, /团队版/)
  assert.match(manualMd, /标签打印/)
})

test('component detail lot form uses responsive rounded card layout', () => {
  const detail = source('../src/components/inventory/InventoryComponentDetail.vue')
  assert.match(detail, /repeat\(auto-fit, minmax\(132px, 1fr\)\)/)
  assert.match(detail, /sourceLabel = \(value\) =>/)
  assert.match(detail, /external_order: '外部'/)
  assert.match(detail, /purchase: '采购'/)
  assert.match(detail, /min-width: 0/)
})

test('manual component drawer renders the edit form even before a component is selected', () => {
  const page = source('../src/views/Components.vue')
  assert.match(page, /const drawerTitle = computed\(\(\) => \(selected\.value \?[\s\S]*: '新增元器件'\)\)/)
  const drawer = page.match(/<el-drawer[\s\S]*?<\/el-drawer>/)?.[0] || ''
  assert.match(drawer, /<template v-if="selected">[\s\S]*inventory-component-detail/)
  assert.match(drawer, /<\/template>\s*<el-form v-if="editing"/)
  assert.match(drawer, /@add-lot="addInventoryLot"/)
  assert.match(drawer, /@ask-ai="askSelectedComponentAi"/)
  assert.match(drawer, /AI 快速新增/)
  assert.match(drawer, /AI 补齐草稿/)
  assert.match(page, /completeFormWithAi/)
  assert.match(page, /aiComponentInfo/)
  assert.match(page, /必填：名称或型号、数量/)
  assert.match(page, /compact-toolbar[\s\S]*grid-template-columns: 1fr 1fr/)
  assert.match(page, /filter-panel[\s\S]*grid-template-columns: 1fr 1fr/)
})

test('team manual add supports AI draft and mobile-first controls', () => {
  const page = source('../src/team/views/Components.vue')
  const api = source('../src/team/api.js')
  const schemas = source('../../backend/app/team_schemas.py')
  const backend = source('../../backend/app/team.py')
  assert.match(page, /AI 快速新增/)
  assert.match(page, /completeManualWithAi/)
  assert.match(page, /manualQuickPrompt/)
  assert.match(page, /必填：名称或型号、库存数量/)
  assert.match(api, /aiComponentInfo/)
  assert.match(schemas, /package: str \| None/)
  assert.match(schemas, /parameters: str \| None/)
  assert.match(backend, /package=str\(values\.get\("package"\)/)
  assert.match(page, /@media \(max-width: 680px\)[\s\S]*team-toolbar \{ display: grid/)
})

test('project page keeps common actions visible and moves dangerous actions into more menu', () => {
  const page = source('../src/views/Projects.vue')
  assert.match(page, /class="toolbar compact-toolbar"/)
  assert.match(page, /<el-button type="primary" :icon="Plus" @click="openBom\(\)">添加物料<\/el-button>/)
  assert.match(page, /handleBomMatchUpload[\s\S]*导入 BOM/)
  assert.match(page, /createPurchasePlan">生成采购计划/)
  assert.match(page, /<el-popover[\s\S]*更多操作[\s\S]*公开项目[\s\S]*编辑项目[\s\S]*项目附件[\s\S]*导出采购 BOM[\s\S]*导出 BOM[\s\S]*完成项目[\s\S]*删除项目/)
})

test('shortage BOM rows show manual substitute suggestions only', () => {
  const page = source('../src/views/Projects.vue')
  const backend = source('../../backend/app/services/substitutions.py')
  assert.match(page, /建议替代/)
  assert.match(page, /仅推荐，不自动替换/)
  assert.match(page, /substitutionSuggestions/)
  assert.match(page, /componentDisplayTitle/)
  assert.match(page, /substitution-warning/)
  assert.match(backend, /同类别/)
  assert.match(backend, /同封装/)
  assert.match(backend, /同标称值/)
  assert.match(backend, /auto_replace": False/)
  assert.doesNotMatch(page, /确认替换/)
})

test('admin dashboard and login policy are wired', () => {
  const router = source('../src/personal/router.js')
  const app = source('../src/personal/App.vue')
  const admin = source('../src/views/AdminDashboard.vue')
  const auth = source('../src/components/AuthPanel.vue')
  const api = source('../src/api/client.js')
  const backend = source('../../backend/app/main.py')
  const authBackend = source('../../backend/app/auth.py')
  assert.match(router, /admin-dashboard/)
  assert.match(app, /to="\/admin"/)
  assert.match(app, /isAdmin/)
  assert.match(admin, /管理员看板/)
  assert.match(admin, /月活用户/)
  assert.match(admin, /常用功能排行/)
  assert.match(admin, /最近界面操作/)
  assert.match(api, /getAdminUsageDashboard/)
  assert.match(backend, /\/api\/admin\/usage-dashboard/)
  assert.match(backend, /monthly_active_users/)
  assert.match(authBackend, /ADMIN_PHONE_NUMBERS/)
  assert.match(auth, /使用条款/)
  assert.match(auth, /隐私协议/)
  assert.match(auth, /termsAccepted/)
  assert.match(auth, /cw_terms_accepted/)
})

test('project public QR has an explicit failure fallback', () => {
  const page = source('../src/views/Projects.vue')
  assert.match(page, /API_BASE/)
  assert.match(page, /apiBasePath\(\)/)
  assert.doesNotMatch(page, /appBasePath\(\)}api\/public\/projects/)
  assert.match(page, /projectQrBroken/)
  assert.match(page, /@error="projectQrBroken = true"/)
  assert.match(page, /二维码加载失败/)
  assert.match(page, /重试二维码/)
  assert.match(page, /复制链接/)
})

test('project risks are collapsed and documented as non-blocking hints', () => {
  const page = source('../src/views/Projects.vue')
  assert.match(page, /projectRiskPreviewLimit = 12/)
  assert.match(page, /visibleProjectRisks/)
  assert.match(page, /查看全部 \$\{currentProjectRisks\.length\} 项风险/)
  assert.match(page, /风险仅作提示，不阻止导入、采购计划、附件和导出。/)
})

test('personal and team BOM imports share an explicit field mapping step', () => {
  const personal = source('../src/views/Projects.vue')
  const team = source('../src/team/views/Projects.vue')
  const mapping = source('../src/shared/components/BomFieldMappingDialog.vue')
  assert.match(personal, /BomFieldMappingDialog/)
  assert.match(team, /BomFieldMappingDialog/)
  assert.match(mapping, /Quantity \/ 数量/)
  assert.match(mapping, /系统仅按表头精确识别/)
})
