#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
BACKEND_DIR="${REPO_DIR}/backend"
FRONTEND_DIR="${REPO_DIR}/frontend"
DATA_DIR="${REPO_DIR}/data"
BACKUP_ROOT="${DATA_DIR}/release-backups"
STAMP="$(date -u +%Y%m%d-%H%M%S)"
BACKUP_DIR="${BACKUP_ROOT}/direct-host-${STAMP}"
SERVICE_NAME="component-warehouse-backend"
MCP_SERVICE_NAME="component-warehouse-mcp"
SERVICE_USER="${SERVICE_USER:-ubuntu}"
SERVICE_GROUP="${SERVICE_GROUP:-ubuntu}"
BACKEND_PORT="${BACKEND_PORT:-18080}"
MCP_PORT="${MCP_PORT:-18082}"
PUBLIC_PROXY_PORT="${PUBLIC_PROXY_PORT:-8080}"
PREVIEW_PORT="${PREVIEW_PORT:-18081}"
ENV_DIR="/etc/component-warehouse"
ENV_FILE="${ENV_DIR}/backend.env"
NGINX_AVAILABLE="/etc/nginx/sites-available/component-warehouse-direct-8080"
NGINX_ENABLED="/etc/nginx/sites-enabled/component-warehouse-direct-8080"
NGINX_PREVIEW_AVAILABLE="/etc/nginx/sites-available/component-warehouse-direct-preview"
NGINX_PREVIEW_ENABLED="/etc/nginx/sites-enabled/component-warehouse-direct-preview"
PUBLISH_ROOT="/var/www/component-warehouse"
HARDWARE_ROOT="/var/www/hardware"
PYTHON_BIN="${PYTHON_BIN:-$(command -v python3.10 || command -v python3)}"
PIP_INDEX_URL="${PIP_INDEX_URL:-http://mirrors.tencentyun.com/pypi/simple}"
PIP_TRUSTED_HOST="${PIP_TRUSTED_HOST:-mirrors.tencentyun.com}"
PIP_EXTRA_INDEX_URL="${PIP_EXTRA_INDEX_URL:-https://pypi.org/simple}"

log() {
  printf '[direct-host] %s\n' "$*"
}

run() {
  log "$*"
  "$@"
}

need_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    printf 'Missing required command: %s\n' "$1" >&2
    exit 1
  fi
}

wait_for_url() {
  local url="$1"
  local label="$2"
  local attempt
  for attempt in $(seq 1 90); do
    if curl -fsS "${url}" >/dev/null 2>&1; then
      log "${label} is ready"
      return 0
    fi
    sleep 1
  done
  printf '%s did not become ready: %s\n' "${label}" "${url}" >&2
  return 1
}

load_root_env_for_frontend() {
  local env_path="${REPO_DIR}/.env"
  [[ -f "${env_path}" ]] || return 0
  while IFS= read -r line || [[ -n "${line}" ]]; do
    line="${line%$'\r'}"
    [[ -z "${line}" || "${line}" =~ ^[[:space:]]*# ]] && continue
    [[ "${line}" == *=* ]] || continue
    local key="${line%%=*}"
    local value="${line#*=}"
    key="$(printf '%s' "${key}" | xargs)"
    [[ "${key}" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || continue
    export "${key}=${value}"
  done < "${env_path}"
}

write_backend_env() {
  local tmp_env
  tmp_env="$(mktemp)"
  if [[ -f "${REPO_DIR}/.env" ]]; then
    awk -F= '
      /^[[:space:]]*($|#)/ { print; next }
      {
        key=$1
        gsub(/^[[:space:]]+|[[:space:]]+$/, "", key)
        if (key ~ /^(DATABASE_URL|TEAM_MEDIA_ROOT|CUSTOM_LABEL_STORAGE_ROOT|TEAM_SECRET_FILE|EDA_STORAGE_ROOT|PROJECT_V2_FILE_ROOT|RETIRE_LEGACY_PERSONAL_PROJECT_API)$/) next
        print
      }
    ' "${REPO_DIR}/.env" > "${tmp_env}"
  fi
  {
    printf '\n# Direct-host absolute runtime paths. Generated by scripts/deploy_direct_host.sh\n'
    printf 'DATABASE_URL=sqlite:////opt/ComponentWarehouse/data/component_warehouse.db\n'
    printf 'TEAM_MEDIA_ROOT=/opt/ComponentWarehouse/data/contest-media\n'
    printf 'CUSTOM_LABEL_STORAGE_ROOT=/opt/ComponentWarehouse/data/custom-labels\n'
    printf 'TEAM_SECRET_FILE=/opt/ComponentWarehouse/data/.contest-invite-secret\n'
    printf 'EDA_STORAGE_ROOT=/opt/ComponentWarehouse/data/eda-library\n'
    printf 'PROJECT_V2_FILE_ROOT=/opt/ComponentWarehouse/data/project-v2-files\n'
    printf 'RETIRE_LEGACY_PERSONAL_PROJECT_API=1\n'
  } >> "${tmp_env}"
  run sudo -n install -d -m 0750 -o root -g "${SERVICE_GROUP}" "${ENV_DIR}"
  run sudo -n install -m 0640 -o root -g "${SERVICE_GROUP}" "${tmp_env}" "${ENV_FILE}"
  rm -f "${tmp_env}"
}

record_baseline() {
  mkdir -p "${BACKUP_DIR}"
  chmod 700 "${BACKUP_DIR}"
  {
    printf '# WXY LAB Hardware direct-host deploy baseline %s UTC\n' "${STAMP}"
    printf '\n## git status\n'
    git -C "${REPO_DIR}" status --short --branch || true
    printf '\n## docker compose ps\n'
    (cd "${REPO_DIR}" && docker compose ps) || true
    printf '\n## disk\n'
    df -h / "${REPO_DIR}" || true
    printf '\n## local health before\n'
    curl -fsS "http://127.0.0.1:${PUBLIC_PROXY_PORT}/component-warehouse/health" || true
    printf '\n## public health before\n'
    curl -kfsS https://wxylab.ltd/component-warehouse/health || true
    printf '\n'
  } > "${BACKUP_DIR}/baseline.txt"
  if [[ -f "${DATA_DIR}/component_warehouse.db" ]]; then
    cp -a "${DATA_DIR}/component_warehouse.db" "${BACKUP_DIR}/component_warehouse.db"
  fi
  if [[ -d "${DATA_DIR}/eda-library" ]]; then
    cp -a "${DATA_DIR}/eda-library" "${BACKUP_DIR}/eda-library"
  fi
  if [[ -d "${BACKEND_DIR}/data/eda-library" ]]; then
    cp -a "${BACKEND_DIR}/data/eda-library" "${BACKUP_DIR}/legacy-backend-eda-library"
  fi
  if [[ -f "${REPO_DIR}/.env" ]]; then
    cp -a "${REPO_DIR}/.env" "${BACKUP_DIR}/env"
    chmod 600 "${BACKUP_DIR}/env"
  fi
  sudo -n nginx -T > "${BACKUP_DIR}/nginx-before.conf" 2>&1 || true
  log "Baseline and backups written to ${BACKUP_DIR}"
}

prepare_backend() {
  if [[ ! -x "${BACKEND_DIR}/.venv/bin/python" ]]; then
    run "${PYTHON_BIN}" -m venv "${BACKEND_DIR}/.venv"
  fi
  run "${BACKEND_DIR}/.venv/bin/python" -m pip install --upgrade pip \
    -i "${PIP_INDEX_URL}" --extra-index-url "${PIP_EXTRA_INDEX_URL}" --trusted-host "${PIP_TRUSTED_HOST}"
  run "${BACKEND_DIR}/.venv/bin/python" -m pip install \
    -i "${PIP_INDEX_URL}" --extra-index-url "${PIP_EXTRA_INDEX_URL}" --trusted-host "${PIP_TRUSTED_HOST}" \
    -r "${BACKEND_DIR}/requirements.txt"
  if [[ ! -x "${BACKEND_DIR}/.venv-mcp/bin/python" ]]; then
    run "${PYTHON_BIN}" -m venv "${BACKEND_DIR}/.venv-mcp"
  fi
  run "${BACKEND_DIR}/.venv-mcp/bin/python" -m pip install --upgrade pip \
    --timeout 1000 --retries 5 \
    -i "${PIP_INDEX_URL}" --extra-index-url "${PIP_EXTRA_INDEX_URL}" --trusted-host "${PIP_TRUSTED_HOST}"
  run "${BACKEND_DIR}/.venv-mcp/bin/python" -m pip install \
    --timeout 1000 --retries 5 \
    -i "${PIP_INDEX_URL}" --extra-index-url "${PIP_EXTRA_INDEX_URL}" --trusted-host "${PIP_TRUSTED_HOST}" \
    -r "${BACKEND_DIR}/requirements-mcp.txt"
  write_backend_env
  run sudo -n install -m 0644 "${REPO_DIR}/deploy/component-warehouse-backend.service" "/etc/systemd/system/${SERVICE_NAME}.service"
  run sudo -n install -m 0644 "${REPO_DIR}/deploy/component-warehouse-mcp.service" "/etc/systemd/system/${MCP_SERVICE_NAME}.service"
  run sudo -n systemctl daemon-reload
}

prepare_frontend() {
  load_root_env_for_frontend
  run npm --prefix "${FRONTEND_DIR}" ci
  run npm --prefix "${FRONTEND_DIR}" run build

  local stage_dir
  stage_dir="$(mktemp -d)"
  mkdir -p "${stage_dir}/personal" "${stage_dir}/team" "${stage_dir}/downloads"
  cp -a "${FRONTEND_DIR}/dist/personal/." "${stage_dir}/personal/"
  cp -a "${FRONTEND_DIR}/dist/team/." "${stage_dir}/team/"

  if docker ps --format '{{.Names}}' | grep -qx 'component-warehouse-frontend'; then
    log "Copying downloads from running Docker frontend container"
    docker cp component-warehouse-frontend:/usr/share/nginx/html/component-warehouse/downloads/. "${stage_dir}/downloads/" || true
  elif [[ -d "${PUBLISH_ROOT}/downloads" ]]; then
    log "Reusing existing published downloads"
    cp -a "${PUBLISH_ROOT}/downloads/." "${stage_dir}/downloads/"
  fi
  if [[ -f "${REPO_DIR}/artifacts/windows-x64/WXY-LAB-Hardware-Setup-x64.exe" ]]; then
    cp -a "${REPO_DIR}/artifacts/windows-x64/WXY-LAB-Hardware-Setup-x64.exe" "${stage_dir}/downloads/"
    cp -a "${REPO_DIR}/artifacts/windows-x64/WXY-LAB-Hardware-Setup-x64.exe.sha256" "${stage_dir}/downloads/"
  fi
  if [[ ! -f "${stage_dir}/downloads/WXY-LAB-Hardware-Setup-x64.exe" || ! -f "${stage_dir}/downloads/WXY-LAB-Hardware-Setup-x64.exe.sha256" ]]; then
    printf 'Windows installer and SHA256 are required before publishing v%s\n' "$(cat "${REPO_DIR}/VERSION")" >&2
    rm -rf "${stage_dir}"
    return 1
  fi

  run sudo -n mkdir -p "${PUBLISH_ROOT}"
  run sudo -n rm -rf "${PUBLISH_ROOT}/personal" "${PUBLISH_ROOT}/team"
  run sudo -n cp -a "${stage_dir}/personal" "${PUBLISH_ROOT}/personal"
  run sudo -n cp -a "${stage_dir}/team" "${PUBLISH_ROOT}/team"
  run sudo -n mkdir -p "${PUBLISH_ROOT}/downloads"
  if find "${stage_dir}/downloads" -mindepth 1 -maxdepth 1 | grep -q .; then
    run sudo -n rm -rf "${PUBLISH_ROOT}/downloads"
    run sudo -n cp -a "${stage_dir}/downloads" "${PUBLISH_ROOT}/downloads"
  fi
  run sudo -n chown -R root:root "${PUBLISH_ROOT}"
  run sudo -n chmod -R a+rX "${PUBLISH_ROOT}"
  run sudo -n rm -rf "${HARDWARE_ROOT}"
  run sudo -n cp -a "${stage_dir}/personal" "${HARDWARE_ROOT}"
  run sudo -n mkdir -p "${HARDWARE_ROOT}/downloads"
  if find "${stage_dir}/downloads" -mindepth 1 -maxdepth 1 | grep -q .; then
    run sudo -n cp -a "${stage_dir}/downloads/." "${HARDWARE_ROOT}/downloads/"
  fi
  run sudo -n chown -R root:root "${HARDWARE_ROOT}"
  run sudo -n chmod -R a+rX "${HARDWARE_ROOT}"
  rm -rf "${stage_dir}"
}

prepare_nginx() {
  run sudo -n install -m 0644 "${REPO_DIR}/deploy/nginx-component-warehouse-8080.conf" "${NGINX_AVAILABLE}"
  local tmp_nginx
  tmp_nginx="$(mktemp)"
  sed "s/listen 127.0.0.1:${PUBLIC_PROXY_PORT};/listen 127.0.0.1:${PREVIEW_PORT};/" \
    "${REPO_DIR}/deploy/nginx-component-warehouse-8080.conf" > "${tmp_nginx}"
  run sudo -n install -m 0644 "${tmp_nginx}" "${NGINX_PREVIEW_AVAILABLE}"
  rm -f "${tmp_nginx}"
  run sudo -n nginx -t
}

prepare_data_permissions() {
  run sudo -n mkdir -p "${DATA_DIR}/contest-media" "${DATA_DIR}/custom-labels" "${DATA_DIR}/eda-library" "${DATA_DIR}/project-v2-files" "${DATA_DIR}/sync-blobs" "${DATA_DIR}/backups"
  run sudo -n chown -R "${SERVICE_USER}:${SERVICE_GROUP}" "${DATA_DIR}"
  if [[ -f "${DATA_DIR}/.contest-invite-secret" ]]; then
    run chmod 600 "${DATA_DIR}/.contest-invite-secret"
  fi
}

start_preview() {
  run sudo -n ln -sfn "${NGINX_PREVIEW_AVAILABLE}" "${NGINX_PREVIEW_ENABLED}"
  run sudo -n systemctl enable "${SERVICE_NAME}"
  run sudo -n systemctl enable "${MCP_SERVICE_NAME}"
  run sudo -n systemctl restart "${SERVICE_NAME}"
  run sudo -n systemctl restart "${MCP_SERVICE_NAME}"
  run sudo -n nginx -t
  run sudo -n systemctl reload nginx
}

verify() {
  wait_for_url "http://127.0.0.1:${BACKEND_PORT}/health" "direct backend"
  wait_for_url "http://127.0.0.1:${MCP_PORT}/health" "OAuth MCP service"
  wait_for_url "http://127.0.0.1:${PREVIEW_PORT}/hardware/health" "direct preview"
  wait_for_url "http://127.0.0.1:${PUBLIC_PROXY_PORT}/component-warehouse/health" "public runtime"
  run systemctl --no-pager --full status "${SERVICE_NAME}"
  run systemctl --no-pager --full status "${MCP_SERVICE_NAME}"
  run curl -fsS "http://127.0.0.1:${BACKEND_PORT}/health"
  run curl -fsS "http://127.0.0.1:${MCP_PORT}/health"
  run curl -fsS "http://127.0.0.1:${PREVIEW_PORT}/.well-known/oauth-protected-resource/hardware/mcp"
  run curl -fsS "http://127.0.0.1:${PREVIEW_PORT}/.well-known/oauth-authorization-server/hardware/oauth"
  run curl -fsS "http://127.0.0.1:${PREVIEW_PORT}/hardware/health"
  run curl -fsS "http://127.0.0.1:${PUBLIC_PROXY_PORT}/component-warehouse/health"
  run curl -kfsS https://wxylab.ltd/component-warehouse/health
  run curl -fsSI "http://127.0.0.1:${PREVIEW_PORT}/hardware/" >/dev/null
  run curl -fsSI "http://127.0.0.1:${PREVIEW_PORT}/hardware/projects" >/dev/null
  run curl -fsSI "http://127.0.0.1:${PREVIEW_PORT}/hardware/sw.js" >/dev/null
  run curl -fsSI "http://127.0.0.1:${PREVIEW_PORT}/component-warehouse/team/" >/dev/null
  run curl -fsSI "http://127.0.0.1:${PREVIEW_PORT}/component-warehouse/team/team-sw.js" >/dev/null
  run curl -fsSI "http://127.0.0.1:${PREVIEW_PORT}/component-warehouse/personal/projects" >/dev/null
  run curl -fsSI "http://127.0.0.1:${PREVIEW_PORT}/hardware/downloads/WXYLAB-AD-Sync-latest-win-x64.zip.sha256" >/dev/null
  run curl -fsSI "http://127.0.0.1:${PREVIEW_PORT}/hardware/downloads/WXY-LAB-Hardware-Setup-x64.exe" >/dev/null
  run curl -fsS "http://127.0.0.1:${PREVIEW_PORT}/hardware/downloads/WXY-LAB-Hardware-Setup-x64.exe.sha256" >/dev/null
}

main() {
  need_cmd sudo
  need_cmd docker
  need_cmd npm
  need_cmd curl
  need_cmd nginx
  run sudo -n true
  record_baseline
  prepare_backend
  prepare_frontend
  prepare_nginx
  prepare_data_permissions
  start_preview
  verify
  log "Direct-host build and preview complete on http://127.0.0.1:${PREVIEW_PORT}/hardware/ ; public runtime is healthy on ${PUBLIC_PROXY_PORT}"
}

main "$@"
